// Copyright (C) 2007 Suneido Software Corp. All rights reserved worldwide.
#(
PLAIN:				0
SQUIGGLE:			1
TT:					2
DIAGONAL:			3
STRIKE:				4
HIDDEN:				5
BOX:				6
ROUNDBOX:			7
STRAIGHTBOX:		8
CONTAINER:			8
DASH:				9

DOTS:				10
SQUIGGLELOW:		11
DOTBOX:				12
SQUIGGLEPIXMAP:		13
COMPOSITIONTHICK:	14
COMPOSITIONTHIN:	15
FULLBOX:			16
TEXTFORE:			17
POINT:				18
POINTCHARACTER:		19

GRADIENT:			20
GRADIENTCENTRE:		21
IME:				32
IME_MAX:			35
MAX:				35
)