// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright Suneido Software Corp. All rights reserved.
// Governed by the MIT license found in the LICENSE file.

package meta

import (
	"sort"

	"github.com/apmckinlay/gsuneido/db19/stor"
	"github.com/apmckinlay/gsuneido/util/assert"
	"github.com/apmckinlay/gsuneido/util/cksum"
)

// list returns a list of the keys in the table
func (ht InfoHamt) list() []string {
	keys := make([]string, 0, 16)
	ht.ForEach(func(it *Info) {
		keys = append(keys, InfoKey(it))
	})
	return keys
}

const blockSizeInfo = 2000
const perFingerInfo = 16

func (ht InfoHamt) Write(st *stor.Stor) uint64 {
	nitems := 0
	size := 3 + 2
	ht.ForEach(func(it *Info) {
		size += it.storSize()
		nitems++
	})
	if nitems == 0 {
		return 0
	}
	nfingers := 1 + nitems/perFingerInfo
	size += 3 * nfingers
	off, buf := st.Alloc(size + cksum.Len)
	w := stor.NewWriter(buf)
	w.Put3(size + cksum.Len)
	w.Put2(nitems)

	keys := ht.list()
	sort.Strings(keys)
	w2 := *w
	for i := 0; i < nfingers; i++ {
		w.Put3(0) // leave room
	}
	fingers := make([]int, 0, nfingers)
	for i, k := range keys {
		if i%16 == 0 {
			fingers = append(fingers, w.Len())
		}
		it, _ := ht.Get(k)
		it.Write(w)
	}
	assert.That(len(fingers) == nfingers)
	assert.That(w.Len() == size)
	for _, f := range fingers {
		w2.Put3(f) // update with actual values
	}
	cksum.Update(buf)
	return off
}

func ReadInfoHamt(st *stor.Stor, off uint64) InfoHamt {
	if off == 0 {
		return InfoHamt{}
	}
	buf := st.Data(off)
	r := stor.NewReader(buf)
	size := r.Get3()
	if size == 0 {
		return InfoHamt{}
	}
	cksum.MustCheck(buf[:size])
	nitems := r.Get2()
	t := InfoHamt{}.Mutable()
	if nitems == 0 {
		return t
	}
	nfingers := 1 + nitems/perFingerInfo
	for i := 0; i < nfingers; i++ {
		r.Get3() // skip the fingers
	}
	for i := 0; i < nitems; i++ {
		t.Put(ReadInfo(st, r))
	}
	return t.Freeze()
}
