version: "2"
run:
  build-tags:
    - "gui"
linters:
  enable:
    - misspell
    - staticcheck
    - govet
    - immutablecheck
  disable:
    - errcheck
  settings:
    govet:
      enable:
        - unsafeptr
    misspell:
      ignore-rules:
        - strat
    staticcheck:
      checks:
        - "all"
        - "-ST1000" # package comment
        - "-ST1001" # dot import
        - "-ST1003" # naming
        - "-ST1005" # error strings
        - "-ST1017" # condition order
        - "-QF1001" # De Morgan's law
        - "-QF1008" # could remove embedded field from selector
    custom:
      immutablecheck:
        type: "module"
        description: Immutable type mutation checker (pls-dont-go)
  exclusions:
    generated: lax
formatters:
  exclusions:
    generated: lax
