// Copyright (C) 2007 Suneido Software Corp. All rights reserved worldwide.
#(
MULTIDESTFILES:			1
CONFIRMMOUSE:			2
SILENT:					4
RENAMEONCOLLISION:		8
NOCONFIRMATION:			16
WANTMAPPINGHANDLE:		32
ALLOWUNDO:				64
FILESONLY:				128
SIMPLEPROGRESS:			256
NOCONFIRMMKDIR:			512
NOERRORUI:				1024
NOCOPYSECURITYATTRIBS:	2048
)