// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package runtime

// activeObserver is the value type.
// It must have an Equal method.

// ActiveObserverList is a list of values
type ActiveObserverList struct {
	list []activeObserver
}

// Push adds a activeObserver to the end of the list
func (il *ActiveObserverList) Push(v activeObserver) {
	il.list = append(il.list, v)
}

// Pop removes the last element of the list
func (il *ActiveObserverList) Pop() {
	var zero activeObserver
	il.list[len(il.list)-1] = zero // for gc
	il.list = il.list[:len(il.list)-1]
}

// Has returns true if the list contains
func (il *ActiveObserverList) Has(v activeObserver) bool {
	for _, x := range il.list {
		if x.Equal(v) {
			return true
		}
	}
	return false
}

// Remove deletes the first occurence of a value
// and returns true if the value was found, otherwise false.
func (il *ActiveObserverList) Remove(v activeObserver) bool {
	for i, x := range il.list {
		if x.Equal(v) {
			var zero activeObserver
			copy(il.list[i:], il.list[i+1:])
			il.list[len(il.list)-1] = zero // for gc
			il.list = il.list[:len(il.list)-1]
			return true
		}
	}
	return false
}
