// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package runtime

// Value is the value type.
// It must have an Equal method.

// ValueList is a list of values
type ValueList struct {
	list []Value
}

// Push adds a Value to the end of the list
func (il *ValueList) Push(v Value) {
	il.list = append(il.list, v)
}

// Pop removes the last element of the list
func (il *ValueList) Pop() {
	var zero Value
	il.list[len(il.list)-1] = zero // for gc
	il.list = il.list[:len(il.list)-1]
}

// Has returns true if the list contains
func (il *ValueList) Has(v Value) bool {
	for _, x := range il.list {
		if x.Equal(v) {
			return true
		}
	}
	return false
}

// Remove deletes the first occurence of a value
// and returns true if the value was found, otherwise false.
func (il *ValueList) Remove(v Value) bool {
	for i, x := range il.list {
		if x.Equal(v) {
			var zero Value
			copy(il.list[i:], il.list[i+1:])
			il.list[len(il.list)-1] = zero // for gc
			il.list = il.list[:len(il.list)-1]
			return true
		}
	}
	return false
}
