// Copyright Suneido Software Corp. All rights reserved.
// Governed by the MIT license found in the LICENSE file.

package query

import (
	. "github.com/apmckinlay/gsuneido/core"
	"github.com/apmckinlay/gsuneido/util/assert"
	"github.com/apmckinlay/gsuneido/util/opt"
)

// ProjectNone produces a single empty row with no columns.
// It results from a Project with no columns.
// It is not generated by the query parser.
// It returns 0 rows when the source is empty, otherwise 1 row.
type ProjectNone struct {
	cache
	source Query
	done   bool
	hasrow opt.Bool
}

var _ Query = (*ProjectNone)(nil)

func (*ProjectNone) String() string {
	return "project-none"
}

func (pn *ProjectNone) Transform() Query {
	return pn
}

func (*ProjectNone) Columns() []string {
	return nil
}

func (*ProjectNone) Keys() [][]string {
	return emptyKey
}

func (*ProjectNone) fastSingle() bool {
	return true
}

func (*ProjectNone) Indexes() [][]string {
	return emptyKey
}

func (pn *ProjectNone) Nrows() (int, int) {
	nr, _ := pn.source.Nrows()
	if nr == 0 {
		return 0, 0
	}
	return 1, 1
}

func (*ProjectNone) knowExactNrows() bool {
	return true
}

func (*ProjectNone) rowSize() int {
	return 0
}

func (*ProjectNone) Order() []string {
	return nil
}

func (*ProjectNone) Fixed() Fixed {
	return nil
}

func (*ProjectNone) Updateable() string {
	return "nothing"
}

func (*ProjectNone) SingleTable() bool {
	return true
}

func (pn *ProjectNone) SetTran(t QueryTran) {
	pn.source.SetTran(t)
	pn.hasrow.UnSet()
}

func (pn *ProjectNone) hasRow() bool {
	if !pn.hasrow.IsSet() {
		row := pn.source.Get(nil, Next)
		pn.hasrow.Set(row != nil)
		pn.source.Rewind()
	}
	return pn.hasrow.Get()
}

func (pn *ProjectNone) optimize(mode Mode, _ Require) (Cost, Cost, any) {
	nrows, _ := pn.source.Nrows()
	frac := 1.0
	if nrows > 1 {
		frac = 1.0 / float64(nrows)
	}
	srcReq := NoneReq(float32(frac))
	fixcost, varcost := Optimize(pn.source, mode, srcReq)
	return fixcost, varcost, nil
}

func (pn *ProjectNone) setApproach(_ Require, _ any, tran QueryTran) {
	nrows, _ := pn.source.Nrows()
	frac := 1.0
	if nrows > 1 {
		frac = 1.0 / float64(nrows)
	}
	srcReq := NoneReq(float32(frac))
	pn.source = SetApproach(pn.source, srcReq, tran)
}

func (pn *ProjectNone) Lookup(_ *Thread, sels Sels) Row {
	assert.That(len(sels) == 0)
	if pn.hasRow() {
		return pnRow
	}
	return nil
}

var pjHeader = SimpleHeader([]string{})

func (*ProjectNone) Header() *Header {
	return pjHeader
}

func (*ProjectNone) Output(*Thread, Record) {
	panic("can't Output to ProjectNone")
}

var pnRow = Row{DbRec{Record: Record("")}}

func (pn *ProjectNone) Get(_ *Thread, _ Dir) Row {
	if !pn.done {
		pn.done = true
		if pn.hasRow() {
			return pnRow
		}
	}
	return nil
}

func (pn *ProjectNone) Rewind() {
	pn.done = false
}

func (pn *ProjectNone) Select(sels Sels) {
	pn.Rewind()
}

func (pn *ProjectNone) Simple(th *Thread) []Row {
	if len(pn.source.Simple(th)) == 0 {
		return nil
	}
	return []Row{pnRow}
}

var noMetrics metrics

func (*ProjectNone) Metrics() *metrics {
	return &noMetrics
}
