// Code generated by "stringer -type=Use"; DO NOT EDIT.

package query

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReqUnordered-0]
	_ = x[ReqOrdered-1]
	_ = x[ReqGrouped-2]
	_ = x[ReqLookup-3]
}

const _Use_name = "ReqUnorderedReqOrderedReqGroupedReqLookup"

var _Use_index = [...]uint8{0, 12, 22, 32, 41}

func (i Use) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Use_index)-1 {
		return "Use(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Use_name[_Use_index[idx]:_Use_index[idx+1]]
}
