// Code generated by "stringer -type=Opcode"; DO NOT EDIT.

package opcodes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Nop-0]
	_ = x[Pop-1]
	_ = x[Dup-2]
	_ = x[Swap-3]
	_ = x[Int-4]
	_ = x[Value-5]
	_ = x[True-6]
	_ = x[False-7]
	_ = x[Zero-8]
	_ = x[One-9]
	_ = x[MinusOne-10]
	_ = x[MaxInt-11]
	_ = x[EmptyStr-12]
	_ = x[Load-13]
	_ = x[Store-14]
	_ = x[LoadStore-15]
	_ = x[Dyload-16]
	_ = x[Global-17]
	_ = x[Get-18]
	_ = x[Put-19]
	_ = x[GetPut-20]
	_ = x[RangeTo-21]
	_ = x[RangeLen-22]
	_ = x[This-23]
	_ = x[Is-24]
	_ = x[Isnt-25]
	_ = x[Match-26]
	_ = x[MatchNot-27]
	_ = x[Lt-28]
	_ = x[Lte-29]
	_ = x[Gt-30]
	_ = x[Gte-31]
	_ = x[Add-32]
	_ = x[Sub-33]
	_ = x[Cat-34]
	_ = x[Mul-35]
	_ = x[Div-36]
	_ = x[Mod-37]
	_ = x[LeftShift-38]
	_ = x[RightShift-39]
	_ = x[BitOr-40]
	_ = x[BitAnd-41]
	_ = x[BitXor-42]
	_ = x[BitNot-43]
	_ = x[Not-44]
	_ = x[UnaryPlus-45]
	_ = x[UnaryMinus-46]
	_ = x[InRange-47]
	_ = x[Or-48]
	_ = x[And-49]
	_ = x[Bool-50]
	_ = x[QMark-51]
	_ = x[In-52]
	_ = x[Cover-53]
	_ = x[Jump-54]
	_ = x[JumpTrue-55]
	_ = x[JumpFalse-56]
	_ = x[JumpIs-57]
	_ = x[JumpIsnt-58]
	_ = x[Iter-59]
	_ = x[ForIn-60]
	_ = x[Throw-61]
	_ = x[Try-62]
	_ = x[Catch-63]
	_ = x[CallFuncDiscard-64]
	_ = x[CallFuncNoNil-65]
	_ = x[CallFuncNilOk-66]
	_ = x[CallMethDiscard-67]
	_ = x[CallMethNoNil-68]
	_ = x[CallMethNilOk-69]
	_ = x[Super-70]
	_ = x[Return-71]
	_ = x[ReturnNil-72]
	_ = x[ReturnThrow-73]
	_ = x[Closure-74]
	_ = x[BlockBreak-75]
	_ = x[BlockContinue-76]
	_ = x[BlockReturn-77]
	_ = x[BlockReturnNil-78]
}

const _Opcode_name = "NopPopDupSwapIntValueTrueFalseZeroOneMinusOneMaxIntEmptyStrLoadStoreLoadStoreDyloadGlobalGetPutGetPutRangeToRangeLenThisIsIsntMatchMatchNotLtLteGtGteAddSubCatMulDivModLeftShiftRightShiftBitOrBitAndBitXorBitNotNotUnaryPlusUnaryMinusInRangeOrAndBoolQMarkInCoverJumpJumpTrueJumpFalseJumpIsJumpIsntIterForInThrowTryCatchCallFuncDiscardCallFuncNoNilCallFuncNilOkCallMethDiscardCallMethNoNilCallMethNilOkSuperReturnReturnNilReturnThrowClosureBlockBreakBlockContinueBlockReturnBlockReturnNil"

var _Opcode_index = [...]uint16{0, 3, 6, 9, 13, 16, 21, 25, 30, 34, 37, 45, 51, 59, 63, 68, 77, 83, 89, 92, 95, 101, 108, 116, 120, 122, 126, 131, 139, 141, 144, 146, 149, 152, 155, 158, 161, 164, 167, 176, 186, 191, 197, 203, 209, 212, 221, 231, 238, 240, 243, 247, 252, 254, 259, 263, 271, 280, 286, 294, 298, 303, 308, 311, 316, 331, 344, 357, 372, 385, 398, 403, 409, 418, 429, 436, 446, 459, 470, 484}

func (i Opcode) String() string {
	if i >= Opcode(len(_Opcode_index)-1) {
		return "Opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Opcode_name[_Opcode_index[i]:_Opcode_index[i+1]]
}
