// Copyright (C) 2012 Suneido Software Corp. All rights reserved worldwide.
#(
NORMAL: 0
BOLD: 1
ITALIC: 2
BOLD_ITALIC: 3
UNDERLINE: 4
BOLD_UNDERLINE: 5
ITALIC_UNDERLINE: 6
BOLD_ITALIC_UNDERLINE: 7
STRIKETHROUGH: 8
STRIKETHROUGH_BOLD: 9
STRIKETHROUGH_ITALIC: 10
STRIKETHROUGH_BOLD_ITALIC: 11
STRIKETHROUGH_UNDERLINE: 12
STRIKETHROUGH_BOLD_UNDERLINE: 13
STRIKETHROUGH_ITALIC_UNDERLINE: 14
STRIKETHROUGH_BOLD_ITALIC_UNDERLINE: 15
)