// Code generated by "stringer -type=Dir"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Only-49]
	_ = x[Next-43]
	_ = x[Prev-45]
	_ = x[Any-64]
}

const (
	_Dir_name_0 = "Next"
	_Dir_name_1 = "Prev"
	_Dir_name_2 = "Only"
	_Dir_name_3 = "Any"
)

func (i Dir) String() string {
	switch {
	case i == 43:
		return _Dir_name_0
	case i == 45:
		return _Dir_name_1
	case i == 49:
		return _Dir_name_2
	case i == 64:
		return _Dir_name_3
	default:
		return "Dir(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
