// Code generated by "stringer -type=Command"; DO NOT EDIT.

package commands

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Abort-0]
	_ = x[Admin-1]
	_ = x[Auth-2]
	_ = x[Check-3]
	_ = x[Close-4]
	_ = x[Commit-5]
	_ = x[Connections-6]
	_ = x[Cursor-7]
	_ = x[Cursors-8]
	_ = x[Dump-9]
	_ = x[Erase-10]
	_ = x[Exec-11]
	_ = x[Strategy-12]
	_ = x[Final-13]
	_ = x[Get-14]
	_ = x[GetOne-15]
	_ = x[Header-16]
	_ = x[Info-17]
	_ = x[Keys-18]
	_ = x[Kill-19]
	_ = x[LibGet-20]
	_ = x[Libraries-21]
	_ = x[Load-22]
	_ = x[Log-23]
	_ = x[Nonce-24]
	_ = x[Order-25]
	_ = x[Output-26]
	_ = x[Query-27]
	_ = x[ReadCount-28]
	_ = x[Action-29]
	_ = x[Rewind-30]
	_ = x[Run-31]
	_ = x[SessionId-32]
	_ = x[Size-33]
	_ = x[Timestamp-34]
	_ = x[Token-35]
	_ = x[Transaction-36]
	_ = x[Transactions-37]
	_ = x[Update-38]
	_ = x[WriteCount-39]
	_ = x[EndSession-40]
	_ = x[Asof-41]
	_ = x[Eof-42]
}

const _Command_name = "AbortAdminAuthCheckCloseCommitConnectionsCursorCursorsDumpEraseExecStrategyFinalGetGetOneHeaderInfoKeysKillLibGetLibrariesLoadLogNonceOrderOutputQueryReadCountActionRewindRunSessionIdSizeTimestampTokenTransactionTransactionsUpdateWriteCountEndSessionAsofEof"

var _Command_index = [...]uint16{0, 5, 10, 14, 19, 24, 30, 41, 47, 54, 58, 63, 67, 75, 80, 83, 89, 95, 99, 103, 107, 113, 122, 126, 129, 134, 139, 145, 150, 159, 165, 171, 174, 183, 187, 196, 201, 212, 224, 230, 240, 250, 254, 257}

func (i Command) String() string {
	if i >= Command(len(_Command_index)-1) {
		return "Command(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Command_name[_Command_index[i]:_Command_index[i+1]]
}
