// Code generated by "stringer -type=Command"; DO NOT EDIT.

package commands

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Abort-0]
	_ = x[Admin-1]
	_ = x[Auth-2]
	_ = x[Check-3]
	_ = x[Close-4]
	_ = x[Commit-5]
	_ = x[Connections-6]
	_ = x[Cursor-7]
	_ = x[Cursors-8]
	_ = x[Erase-9]
	_ = x[Exec-10]
	_ = x[Strategy-11]
	_ = x[Final-12]
	_ = x[Get-13]
	_ = x[GetOne-14]
	_ = x[Header-15]
	_ = x[Info-16]
	_ = x[Keys-17]
	_ = x[Kill-18]
	_ = x[LibGet-19]
	_ = x[Libraries-20]
	_ = x[Log-21]
	_ = x[Nonce-22]
	_ = x[Order-23]
	_ = x[Output-24]
	_ = x[Query-25]
	_ = x[ReadCount-26]
	_ = x[Action-27]
	_ = x[Rewind-28]
	_ = x[Run-29]
	_ = x[SessionId-30]
	_ = x[Size-31]
	_ = x[Timestamp-32]
	_ = x[Token-33]
	_ = x[Transaction-34]
	_ = x[Transactions-35]
	_ = x[Update-36]
	_ = x[WriteCount-37]
	_ = x[EndSession-38]
	_ = x[Asof-39]
}

const _Command_name = "AbortAdminAuthCheckCloseCommitConnectionsCursorCursorsEraseExecStrategyFinalGetGetOneHeaderInfoKeysKillLibGetLibrariesLogNonceOrderOutputQueryReadCountActionRewindRunSessionIdSizeTimestampTokenTransactionTransactionsUpdateWriteCountEndSessionAsof"

var _Command_index = [...]uint8{0, 5, 10, 14, 19, 24, 30, 41, 47, 54, 59, 63, 71, 76, 79, 85, 91, 95, 99, 103, 109, 118, 121, 126, 131, 137, 142, 151, 157, 163, 166, 175, 179, 188, 193, 204, 216, 222, 232, 242, 246}

func (i Command) String() string {
	if i >= Command(len(_Command_index)-1) {
		return "Command(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Command_name[_Command_index[i]:_Command_index[i+1]]
}
