// Code generated by "stringer -type=Command"; DO NOT EDIT.

package commands

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Abort-0]
	_ = x[Admin-1]
	_ = x[Auth-2]
	_ = x[Check-3]
	_ = x[Close-4]
	_ = x[Commit-5]
	_ = x[Connections-6]
	_ = x[Cursor-7]
	_ = x[Cursors-8]
	_ = x[Erase-9]
	_ = x[Exec-10]
	_ = x[Strategy-11]
	_ = x[Final-12]
	_ = x[Get-13]
	_ = x[GetOne-14]
	_ = x[Header-15]
	_ = x[Info-16]
	_ = x[Keys-17]
	_ = x[Kill-18]
	_ = x[LibGet-19]
	_ = x[Libraries-20]
	_ = x[Log-21]
	_ = x[Order-22]
	_ = x[Output-23]
	_ = x[Query-24]
	_ = x[ReadCount-25]
	_ = x[Action-26]
	_ = x[Rewind-27]
	_ = x[SessionId-28]
	_ = x[Size-29]
	_ = x[Timestamp-30]
	_ = x[Transaction-31]
	_ = x[Transactions-32]
	_ = x[Update-33]
	_ = x[WriteCount-34]
	_ = x[EndSession-35]
	_ = x[Asof-36]
}

const _Command_name = "AbortAdminAuthCheckCloseCommitConnectionsCursorCursorsEraseExecStrategyFinalGetGetOneHeaderInfoKeysKillLibGetLibrariesLogOrderOutputQueryReadCountActionRewindSessionIdSizeTimestampTransactionTransactionsUpdateWriteCountEndSessionAsof"

var _Command_index = [...]uint8{0, 5, 10, 14, 19, 24, 30, 41, 47, 54, 59, 63, 71, 76, 79, 85, 91, 95, 99, 103, 109, 118, 121, 126, 132, 137, 146, 152, 158, 167, 171, 180, 191, 203, 209, 219, 229, 233}

func (i Command) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Command_index)-1 {
		return "Command(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Command_name[_Command_index[idx]:_Command_index[idx+1]]
}
