// Code generated by "stringer -type=opType"; DO NOT EDIT.

package regex2

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[opChar-1]
	_ = x[opCharIgnoreCase-2]
	_ = x[opJump-3]
	_ = x[opSplitFirst-4]
	_ = x[opSplitLast-5]
	_ = x[opAny-6]
	_ = x[opHalfSet-7]
	_ = x[opFullSet-8]
	_ = x[opListSet-9]
	_ = x[opWordStart-10]
	_ = x[opWordEnd-11]
	_ = x[opLineStart-12]
	_ = x[opLineEnd-13]
	_ = x[opStrStart-14]
	_ = x[opStrEnd-15]
	_ = x[opSave-16]
	_ = x[opStop-17]
}

const _opType_name = "opCharopCharIgnoreCaseopJumpopSplitFirstopSplitLastopAnyopHalfSetopFullSetopListSetopWordStartopWordEndopLineStartopLineEndopStrStartopStrEndopSaveopStop"

var _opType_index = [...]uint8{0, 6, 22, 28, 40, 51, 56, 65, 74, 83, 94, 103, 114, 123, 133, 141, 147, 153}

func (i opType) String() string {
	i -= 1
	if i >= opType(len(_opType_index)-1) {
		return "opType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _opType_name[_opType_index[i]:_opType_index[i+1]]
}
