// Copyright (C) 2013 Suneido Software Corp. All rights reserved worldwide.
// SuJsWebTest
Test
	{
	Test_Main()
		{
		q = new Queue()
		q.Enqueue(1)
		Assert(q.List() is:#(1))
		Assert(q.Dequeue() is:1)
		Assert(q.List() is:#())
		q.Enqueue(1)
		Assert(q.Front() is:1)
		Assert(q.Back() is:1)
		q.Enqueue(2)
		Assert(q.List() is:#(1 2))
		Assert(q.Front() is:1)
		Assert(q.Back() is:2)
		Assert(q.Dequeue() is:1)
		Assert(q.List() is:#(2))
		Assert(q.Front() is:2)
		Assert(q.Back() is:2)
		Assert(q.Dequeue() is:2)
		Assert(q.List() is:#())
		Assert({ q.Dequeue() } throws:'Queue empty')
		Assert({ q.Front() } throws:'Queue empty')
		Assert({ q.Back() } throws:'Queue empty')
		q.Enqueue(1)
		q.Enqueue(0)
		q.Enqueue(1)
		q.Enqueue(2)
		q.Enqueue(3)
		Assert(q.Front() is:1)
		Assert(q.Back() is:3)
		Assert(q.Dequeue() is:1)
		Assert(q.Front() is:0)
		Assert(q.Back() is:3)
		Assert(q.Count() is:4)
		Assert(q.Dequeue() is:0)
		Assert(q.Front() is:1)
		Assert(q.Back() is:3)
		Assert(q.Count() is:3)
		Assert(q.List() is:#(1 2 3))
		Assert(q.ToString() is:"Queue(1, 2, 3)")
		q.Dequeue()
		q.Dequeue()
		q.Dequeue()
		Assert(q.Count() is:0)
		Assert({ q.Dequeue() } throws:'Queue empty')
		Assert({ q.Front() } throws:'Queue empty')
		Assert({ q.Back() } throws:'Queue empty')
		}
	}