// Copyright (C) 2017 Suneido Software Corp. All rights reserved worldwide.
function(node)
	{
	return TdopIsConstant(node) or node.Token in (TDOPTOKEN.IDENTIFIER,
		TDOPTOKEN.MEMBEROP, TDOPTOKEN.TRINARYOP, TDOPTOKEN.BINARYOP, TDOPTOKEN.UNARYOP,
		TDOPTOKEN.INOP, TDOPTOKEN.NOTINOP, TDOPTOKEN.RVALUE, TDOPTOKEN.CALL,
		TDOPTOKEN.PREINCDEC, TDOPTOKEN.POSTINCDEC, TDOPTOKEN.BLOCK, TDOPTOKEN.SUBSCRIPT)
	}