// Copyright (C) 2026 Suneido Software Corp. All rights reserved worldwide.
// BuiltDate > 20260825
function()
	{
	return TypeChecker.RegisterSignatures(#(
		// ---- object ----
		(receiver: object, name: DeleteIf, sig: "(block) :object"),
		(receiver: object, name: FindAll, sig: "(value) :object"),
		(receiver: object, name: FindAllIf, sig: "(block) :object"),
		(receiver: object, name: Empty?, sig: "() :boolean"),
		(receiver: object, name: NotEmpty?, sig: "() :boolean"),
		(receiver: object, name: HasNamed?, sig: "() :boolean"),
		(receiver: object, name: Map!, sig: "(block) :object"),
		(receiver: object, name: Map, sig: "(block) :object"),
		(receiver: object, name: Map2, sig: "(block) :object"),
		(receiver: object, name: MapMembers, sig: "(block) :object"),
		(receiver: object, name: FlatMap, sig: "(block) :object"),
		(receiver: object, name: First, sig: "() :unknown"),
		(receiver: object, name: Last, sig: "() :unknown"),
		(receiver: object, name: MinWith, sig: "(block) :unknown"),
		(receiver: object, name: MaxWith, sig: "(block) :unknown"),
		(receiver: object, name: Project, sig: "(@fields) :object"),
		(receiver: object, name: ProjectValues, sig: "(@fields) :object"),
		(receiver: object, name: ListToNamed, sig: "(@fields) :object"),
		(receiver: object, name: ListToMembers, sig: "() :object"),
		(receiver: object, name: Flatten, sig: "() :object"),
		(receiver: object, name: Intersects?, sig: "(other) :boolean"),
		(receiver: object, name: Disjoint?, sig: "(other) :boolean"),
		(receiver: object, name: Intersect, sig: "(other) :object"),
		(receiver: object, name: Difference, sig: "(other) :object"),
		(receiver: object, name: Union, sig: "(other) :object"),
		(receiver: object, name: Subset?, sig: "(other) :boolean"),
		(receiver: object, name: MergeUnion, sig: "(other) :object"),
		(receiver: object, name: DuplicateValues, sig: "() :object"),
		(receiver: object, name: FindOne, sig: "(block) :false|unknown"),
		(receiver: object, name: FindIf, sig: "(block) :false|unknown"),
		(receiver: object, name: FindLastIf, sig: "(block) :false|unknown"),
		(receiver: object, name: MembersIf, sig: "(block) :object"),
		(receiver: object, name: Val_or_func, sig: "(member) :unknown"),
		(receiver: object, name: Merge, sig: "(ob) :object"),
		(receiver: object, name: MergeNew, sig: "(ob) :object"),
		(receiver: object, name: SafeMembers, sig: "() :object"),
		(receiver: object, name: Replace, sig: "(oldvalue, newvalue) :object"),
		(receiver: object, name: JoinCSV, sig: "(fields = false) :string"),
		(receiver: object, name: Sum, sig: "() :number"),
		(receiver: object, name: SumWith, sig: "(block) :number"),
		(receiver: object, name: Fold, sig: "(val, block) :unknown"),
		(receiver: object, name: Reduce, sig: "(block) :unknown"),
		(receiver: object, name: Remove1, sig: "(x) :unknown"),
		(receiver: object, name: Remove, sig: "(@values) :object"),
		(receiver: object, name: RemoveIf, sig: "(block) :object"),
		(receiver: object, name: Without, sig: "(@values) :object"),
		(receiver: object, name: WithoutFields, sig: "(@fields) :object"),
		(receiver: object, name: Swap, sig: "(idx1, idx2) :object"),
		(receiver: object, name: AddUnique, sig: "(value) :object"),
		(receiver: object, name: Filter, sig: "(block) :object"),
		(receiver: object, name: Zip, sig: "() :object"),
		(receiver: object, name: UniqueValues, sig: "() :object"),
		(receiver: object, name: Append, sig: "(ob) :object"),
		(receiver: object, name: Every?, sig: "(block) :boolean"),
		(receiver: object, name: Any?, sig: "(block) :boolean"),
		(receiver: object, name: HasIf?, sig: "(block) :boolean"),
		(receiver: object, name: Shuffle!, sig: "() :object"),
		(receiver: object, name: AddMany!, sig: "(value, n) :object"),
		(receiver: object, name: Each, sig: "(block) :object"),
		(receiver: object, name: Each2, sig: "(block) :object"),
		(receiver: object, name: SortWith!, sig: "(block) :object"),
		(receiver: object, name: Extract,
			sig: "(member, x = #extract_no_default) :unknown"),
		(receiver: object, name: Count, sig: "(value = #(0)) :number"),
		(receiver: object, name: CountIf, sig: "(block) :number"),
		(receiver: object, name: Sorted?, sig: "(block = false) :boolean"),
		(receiver: object, name: Trim!, sig: "(@values) :object"),
		(receiver: object, name: HasNonEmptyMember?, sig: "(members) :boolean"),
		(receiver: object, name: BinarySearch?, sig: "(value) :boolean"),
		(receiver: object, name: GetDifferences, sig: "(ob) :object"),
		(receiver: object, name: GetInit, sig: "(member, block) :unknown"),
		(receiver: object, name: Take, sig: "(n) :object"),
		(receiver: object, name: Drop, sig: "(n) :object"),
		(receiver: object, name: Nth, sig: "(n) :unknown"),
		(receiver: object, name: Concat, sig: "(@iterables) :object"),
		(receiver: object, name: AddTo, sig: "(ob) :unknown"),
		(receiver: object, name: Instantiate, sig: "() :object"),
		(receiver: object, name: Grep, sig: "(regex, block = false) :object"),
		(receiver: object, name: DeepCopy, sig: "(nesting = 0) :object"),
		(receiver: object, name: DeepReplaceReferences!,
			sig: "(oldName, newName, nesting = 0) :unknown"),
		(receiver: object, name: RandVal, sig: "() :unknown"),
		(receiver: object, name: EqualSet?, sig: "(that) :boolean"),

		// ---- string ----
		(receiver: string, name: As, sig: "(e) :string"),
		(receiver: string, name: LineCount, sig: "() :number"),
		(receiver: string, name: FirstLine, sig: "() :string"),
		(receiver: string, name: Lines, sig: "() :object"),
		(receiver: string, name: RemoveBlankLines, sig: "() :string"),
		(receiver: string, name: RemovePrefix, sig: "(prefix) :string"),
		(receiver: string, name: RemoveSuffix, sig: "(suffix) :string"),
		(receiver: string, name: ChangeEol, sig: "(eol) :string"),
		(receiver: string, name: LineFromPosition, sig: "(pos) :number"),
		(receiver: string, name: LineAtPosition, sig: "(pos) :string"),
		(receiver: string, name: StartPositionOfLine, sig: "(line) :number"),
		(receiver: string, name: Capitalize, sig: "() :string"),
		(receiver: string, name: UnCapitalize, sig: "() :string"),
		(receiver: string, name: CapitalizeWords, sig: "(lower = true) :string"),
		(receiver: string, name: Trim, sig: "(chars = ' \t\r\n') :string"),
		(receiver: string, name: LeftTrim, sig: "(chars = ' \t\r\n') :string"),
		(receiver: string, name: RightTrim, sig: "(chars = ' \t\r\n') :string"),
		(receiver: string, name: SplitCSV,
			sig: "(fields = false, string_vals = false) :object"),
		(receiver: string, name: SplitFixedLength, sig: "(map) :object"),
		(receiver: string, name: ReplaceSubstr, sig: "(i, n, s) :string"),
		(receiver: string, name: LeftFill, sig: "(minSize, char = ' ') :string"),
		(receiver: string, name: TruncateLeftFill, sig: "(size, char = ' ') :string"),
		(receiver: string, name: RightFill, sig: "(minSize, char = ' ') :string"),
		(receiver: string, name: TruncateRightFill, sig: "(size, char = ' ') :string"),
		(receiver: string, name: Center, sig: "(minSize, char = ' ') :string"),
		(receiver: string, name: SplitOnFirst, sig: "(delimiter = ' ') :object"),
		(receiver: string, name: SplitOnLast, sig: "(delimiter = ' ') :object"),
		(receiver: string, name: BeforeFirst, sig: "(delimiter) :string"),
		(receiver: string, name: AfterFirst, sig: "(delimiter) :string"),
		(receiver: string, name: BeforeLast, sig: "(delimiter) :string"),
		(receiver: string, name: AfterLast, sig: "(delimiter) :string"),
		(receiver: string, name: Capitalized?, sig: "() :boolean"),
		(receiver: string, name: FindRx, sig: "(rx) :number"),
		(receiver: string, name: FindRxLast, sig: "(rx) :false|number"),
		(receiver: string, name: ExtractAll, sig: "(pattern) :false|object"),
		(receiver: string, name: WrapLines, sig: "(width) :object"),
		(receiver: string, name: Divide, sig: "(n = 1) :object"),
		(receiver: string, name: White?, sig: "() :boolean"),
		(receiver: string, name: Blank?, sig: "() :boolean"),
		(receiver: string, name: In?, sig: "(x) :boolean"),
		(receiver: string, name: Base64Encode, sig: "() :string"),
		(receiver: string, name: Base64Decode, sig: "() :string"),
		(receiver: string, name: Xor, sig: "(key) :string"),
		(receiver: string, name: GlobalName?, sig: "() :boolean"),
		(receiver: string, name: LocalName?, sig: "() :boolean"),
		(receiver: string, name: Identifier?, sig: "() :boolean"),
		(receiver: string, name: DynamicName?, sig: "() :boolean"),
		(receiver: string, name: ForEachMatch, sig: "(pat, block) :unknown"),
		(receiver: string, name: ForEach1of, sig: "(chars, block) :unknown"),
		(receiver: string, name: SafeEval, sig: "() :unknown"),
		(receiver: string, name: Map, sig: "(block) :string"),
		(receiver: string, name: Escape, sig: "() :string"),
		(receiver: string, name: Ellipsis, sig: "(maxLength, atEnd = false) :string"),
		(receiver: string, name: Has1of?, sig: "(chars) :boolean"),
		(receiver: string, name: UniqueChars, sig: "() :string"),
		(receiver: string, name: StripInvalidChars, sig: "() :string"),
		(receiver: string, name: RandChar, sig: "() :string"),
		(receiver: string, name: Shuffle, sig: "() :string"),

		// ---- number ----
		(receiver: number, name: Ceiling, sig: "() :number"),
		(receiver: number, name: Floor, sig: "() :number"),
		(receiver: number, name: Abs, sig: "() :number"),
		(receiver: number, name: PercentToDecimal, sig: "() :number"),
		(receiver: number, name: DecimalToPercent, sig: "(round = 0) :number"),
		(receiver: number, name: ToWords, sig: "() :string"),
		(receiver: number, name: EnFrancais, sig: "() :string"),
		(receiver: number, name: ToWordsFrench, sig: "() :string"),
		(receiver: number, name: ToWordsDutch, sig: "() :string"),
		(receiver: number, name: ToWordSpanish, sig: "() :string"),
		(receiver: number, name: ToWordsItalian, sig: "() :string"),
		(receiver: number, name: ToWordsSimple, sig: "() :string"),
		(receiver: number, name: Pad, sig: "(minSize, char = '0') :string"),
		(receiver: number, name: Factorial, sig: "() :number"),
		(receiver: number, name: Int?, sig: "() :boolean"),
		(receiver: number, name: IntDigits, sig: "() :number"),
		(receiver: number, name: FracDigits, sig: "() :number"),
		(receiver: number, name: EuroFormat, sig: "(mask) :string"),
		(receiver: number, name: DollarFormat, sig: "(mask) :string"),
		(receiver: number, name: Even?, sig: "() :boolean"),
		(receiver: number, name: Odd?, sig: "() :boolean"),
		(receiver: number, name: Sign, sig: "() :number"),
		(receiver: number, name: RoundToPrecision, sig: "(p) :number"),
		(receiver: number, name: RoundToNearest, sig: "(nearest = 1) :number"),
		(receiver: number, name: ToRGB, sig: "() :object"),
		(receiver: number, name: Times, sig: "(block) :unknown"),
		(receiver: number, name: MinutesInMs, sig: "() :number"),
		(receiver: number, name: SecondsInMs, sig: "() :number"),
		(receiver: number, name: SecondsInHours, sig: "() :number"),
		(receiver: number, name: HoursInSeconds, sig: "() :number"),
		(receiver: number, name: HoursInMinutes, sig: "() :number"),
		(receiver: number, name: SecondsInMinutes, sig: "() :number"),
		(receiver: number, name: InchesInTwips, sig: "() :number"),
		(receiver: number, name: TwipsInInch, sig: "() :number"),
		(receiver: number, name: InchesInCanvasUnit, sig: "() :number"),
		(receiver: number, name: Kb, sig: "() :number"),
		(receiver: number, name: Mb, sig: "() :number"),
		(receiver: number, name: Gb, sig: "() :number"),
		(receiver: number, name: SafeEval, sig: "() :number"),
		(receiver: number, name: Of, sig: "(block) :object"),
		(receiver: number, name: OfStr, sig: "(block) :string"),

		// ---- date ----
		(receiver: date, name: Format, sig: "(format) :string"),
		(receiver: date, name: translate, sig: "(s) :string"),
		(receiver: date, name: ShortDate, sig: "() :string"),
		(receiver: date, name: LongDate, sig: "() :string"),
		(receiver: date, name: Time, sig: "() :string"),
		(receiver: date, name: DayOfYear, sig: "() :number"),
		(receiver: date, name: NoTime, sig: "() :date"),
		(receiver: date, name: NoTime?, sig: "() :boolean"),
		(receiver: date, name: StartOfDay, sig: "() :date"),
		(receiver: date, name: EndOfDay, sig: "() :date"),
		(receiver: date, name: Replace, sig: "(@args) :date"),
		(receiver: date, name: MinusMinutes, sig: "(date) :number"),
		(receiver: date, name: MinusHours, sig: "(date) :number"),
		(receiver: date, name: MinusMonths, sig: "(date) :number"),
		(receiver: date, name: ShortDateTime, sig: "() :string"),
		(receiver: date, name: ShortDateTimeSec, sig: "() :string"),
		(receiver: date, name: StdShortDate, sig: "() :string"),
		(receiver: date, name: StdShortDateTime, sig: "() :string"),
		(receiver: date, name: StdShortDateTimeSec, sig: "() :string"),
		(receiver: date, name: LongDateTime, sig: "() :string"),
		(receiver: date, name: StartOfYear, sig: "() :date"),
		(receiver: date, name: EndOfMonth, sig: "() :date"),
		(receiver: date, name: EndOfMonthDay, sig: "() :number"),
		(receiver: date, name: WeekNumber, sig: "(firstday = 'sun') :number"),
		(receiver: date, name: WeekStart, sig: "(firstday = 'sun') :date"),
		(receiver: date, name: Quarter, sig: "() :number"),
		(receiver: date, name: IsoWeekDay, sig: "() :string"),
		(receiver: date, name: isLeapYear?, sig: "(year) :boolean"),
		(receiver: date, name: GMTime, sig: "() :date"),
		(receiver: date, name: GMTimeToLocal, sig: "() :date"),
		(receiver: date, name: UTC, sig: "(gmtBias = false) :string"),
		(receiver: date, name: Minus, sig: "(@args) :date"),
		(receiver: date, name: InternetFormat, sig: "() :string"),
		(receiver: date, name: UnixTime, sig: "() :number"),
		(receiver: date, name: FromUnix, sig: "(s) :date")
		))
	}
