// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package tr

// TrsetCache is a cache with a crude approximation of LRU.
// Working set should fit in size.
// NOT thread safe.
type TrsetCache struct {
	old   map[string]trset
	cur   map[string]trset
	size  int
	fn    func(string) trset
	nget  int
	nmiss int
}

func NewTrsetCache(size int, fn func(string) trset) *TrsetCache {
	return &TrsetCache{cur: make(map[string]trset, size),
		old: make(map[string]trset), size: size, fn: fn}
}

func (c *TrsetCache) Get(key string) trset {
	c.nget++
	val, ok := c.cur[key]
	if ok {
		return val
	}
	val, ok = c.old[key]
	if !ok {
		c.nmiss++
		val = c.fn(key)
	}
	if len(c.cur) >= c.size {
		c.old = c.cur
		c.cur = make(map[string]trset, c.size)
	}
	c.cur[key] = val
	return val
}

func (c *TrsetCache) NGet() int {
	return c.nget
}

func (c *TrsetCache) NMiss() int {
	return c.nmiss
}
