// Copyright (C) 2013 Suneido Software Corp. All rights reserved worldwide.
// 3D edge styles
#(
RAISED: 0x0005 // BDR.RAISEDOUTER | BDR.RAISEDINNER
SUNKEN: 0x000a // BDR.SUNKENOUTER | BDR.SUNKENINNER
ETCHED: 0x0006 // BDR.SUNKENOUTER | BDR.RAISEDINNER
BUMP:   0x0009 // BDR.RAISEDOUTER | BDR.SUNKENINNER
)