// Code generated by "stringer -type=opType"; DO NOT EDIT.

package regex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[opChar-1]
	_ = x[opCharIgnoreCase-2]
	_ = x[opJump-3]
	_ = x[opSplitNext-4]
	_ = x[opSplitJump-5]
	_ = x[opAny-6]
	_ = x[opAnyNotNL-7]
	_ = x[opHalfSet-8]
	_ = x[opFullSet-9]
	_ = x[opListSet-10]
	_ = x[opWordStart-11]
	_ = x[opWordEnd-12]
	_ = x[opLineStart-13]
	_ = x[opLineEnd-14]
	_ = x[opStrStart-15]
	_ = x[opStrEnd-16]
	_ = x[opSave-17]
	_ = x[opDoneSave1-18]
	_ = x[opOnePass-19]
	_ = x[opBranchNext-20]
	_ = x[opBranchJump-21]
	_ = x[opLiteralSubstr-22]
	_ = x[opLiteralPrefix-23]
	_ = x[opLiteralSuffix-24]
	_ = x[opLiteralEqual-25]
	_ = x[opPrefix-26]
}

const _opType_name = "opCharopCharIgnoreCaseopJumpopSplitNextopSplitJumpopAnyopAnyNotNLopHalfSetopFullSetopListSetopWordStartopWordEndopLineStartopLineEndopStrStartopStrEndopSaveopDoneSave1opOnePassopBranchNextopBranchJumpopLiteralSubstropLiteralPrefixopLiteralSuffixopLiteralEqualopPrefix"

var _opType_index = [...]uint16{0, 6, 22, 28, 39, 50, 55, 65, 74, 83, 92, 103, 112, 123, 132, 142, 150, 156, 167, 176, 188, 200, 215, 230, 245, 259, 267}

func (i opType) String() string {
	i -= 1
	if i >= opType(len(_opType_index)-1) {
		return "opType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _opType_name[_opType_index[i]:_opType_index[i+1]]
}
