// Copyright (C) 2025 Suneido Software Corp. All rights reserved worldwide.
// extacted from commonmark-spec@0.31.2
#(
#(id: 1, markdown: "\tfoo\tbaz\t\tbim\n", html: "<pre><code>foo\xe2\x86\x92baz\xe2\x86\x92\xe2\x86\x92bim\n</code></pre>\n")
#(id: 2, markdown: "  \tfoo\tbaz\t\tbim\n", html: "<pre><code>foo\xe2\x86\x92baz\xe2\x86\x92\xe2\x86\x92bim\n</code></pre>\n")
#(id: 3, markdown: "    a\ta\n    \xe1\xbd\x90\ta\n", html: "<pre><code>a\xe2\x86\x92a\n\xe1\xbd\x90\xe2\x86\x92a\n</code></pre>\n")
#(id: 4, markdown: "  - foo\n\n\tbar\n", html: "<ul>\n<li>\n<p>foo</p>\n<p>bar</p>\n</li>\n</ul>\n")
#(id: 5, markdown: "- foo\n\n\t\tbar\n", html: "<ul>\n<li>\n<p>foo</p>\n<pre><code>  bar\n</code></pre>\n</li>\n</ul>\n")
#(id: 6, markdown: ">\t\tfoo\n", html: "<blockquote>\n<pre><code>  foo\n</code></pre>\n</blockquote>\n")
#(id: 7, markdown: "-\t\tfoo\n", html: "<ul>\n<li>\n<pre><code>  foo\n</code></pre>\n</li>\n</ul>\n")
#(id: 8, markdown: "    foo\n\tbar\n", html: "<pre><code>foo\nbar\n</code></pre>\n")
#(id: 9, markdown: " - foo\n   - bar\n\t - baz\n", html: "<ul>\n<li>foo\n<ul>\n<li>bar\n<ul>\n<li>baz</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n")
#(id: 10, markdown: "#\tFoo\n", html: "<h1>Foo</h1>\n")
#(id: 11, markdown: "*\t*\t*\t\n", html: "<hr />\n")
#(id: 12, markdown: "\\!\\\"\\#\\$\\%\\&\\'\\(\\)\\*\\+\\,\\-\\.\\/\\:\\;\\<\\=\\>\\?\\@\\[\\\\\\]\\^\\_\\`\\{\\|\\}\\~\n", html: "<p>!&quot;#$%&amp;'()*+,-./:;&lt;=&gt;?@[\\]^_`{|}~</p>\n")
#(id: 13, markdown: "\\\t\\A\\a\\ \\3\\\xcf\x86\\\xc2\xab\n", html: "<p>\\\xe2\x86\x92\\A\\a\\ \\3\\\xcf\x86\\\xc2\xab</p>\n")
#(id: 14, markdown: '\\*not emphasized*\n\\<br/> not a tag\n\\[not a link](/foo)\n\\`not code`\n1\\. not a list\n\\* not a list\n\\# not a heading\n\\[foo]: /url "not a reference"\n\\&ouml; not a character entity\n', html: "<p>*not emphasized*\n&lt;br/&gt; not a tag\n[not a link](/foo)\n`not code`\n1. not a list\n* not a list\n# not a heading\n[foo]: /url &quot;not a reference&quot;\n&amp;ouml; not a character entity</p>\n")
#(id: 15, markdown: "\\\\*emphasis*\n", html: "<p>\\<em>emphasis</em></p>\n")
#(id: 16, markdown: "foo\\\nbar\n", html: "<p>foo<br />\nbar</p>\n")
#(id: 17, markdown: "`` \\[\\` ``\n", html: "<p><code>\\[\\`</code></p>\n")
#(id: 18, markdown: "    \\[\\]\n", html: "<pre><code>\\[\\]\n</code></pre>\n")
#(id: 19, markdown: "~~~\n\\[\\]\n~~~\n", html: "<pre><code>\\[\\]\n</code></pre>\n")
#(id: 20, markdown: "<https://example.com?find=\\*>\n", html: '<p><a href="https://example.com?find=%5C*">https://example.com?find=\\*</a></p>\n')
#(id: 21, markdown: '<a href="/bar\\/)">\n', html: '<a href="/bar\\/)">\n')
#(id: 22, markdown: '[foo](/bar\\* "ti\\*tle")\n', html: '<p><a href="/bar*" title="ti*tle">foo</a></p>\n')
#(id: 23, markdown: '[foo]\n\n[foo]: /bar\\* "ti\\*tle"\n', html: '<p><a href="/bar*" title="ti*tle">foo</a></p>\n')
#(id: 24, markdown: "``` foo\\+bar\nfoo\n```\n", html: '<pre><code class="language-foo+bar">foo\n</code></pre>\n')
#(id: 25, markdown: "&nbsp; &amp; &copy; &AElig; &Dcaron;\n&frac34; &HilbertSpace; &DifferentialD;\n&ClockwiseContourIntegral; &ngE;\n", html: "<p>\xc2\xa0 &amp; \xc2\xa9 \xc3\x86 \xc4\x8e\n\xc2\xbe \xe2\x84\x8b \xe2\x85\x86\n\xe2\x88\xb2 \xe2\x89\xa7\xcc\xb8</p>\n")
#(id: 26, markdown: "&#35; &#1234; &#992; &#0;\n", html: "<p># \xd3\x92 \xcf\xa0 \xef\xbf\xbd</p>\n")
#(id: 27, markdown: "&#X22; &#XD06; &#xcab;\n", html: "<p>&quot; \xe0\xb4\x86 \xe0\xb2\xab</p>\n")
#(id: 28, markdown: "&nbsp &x; &#; &#x;\n&#87654321;\n&#abcdef0;\n&ThisIsNotDefined; &hi?;\n", html: "<p>&amp;nbsp &amp;x; &amp;#; &amp;#x;\n&amp;#87654321;\n&amp;#abcdef0;\n&amp;ThisIsNotDefined; &amp;hi?;</p>\n")
#(id: 29, markdown: "&copy\n", html: "<p>&amp;copy</p>\n")
#(id: 30, markdown: "&MadeUpEntity;\n", html: "<p>&amp;MadeUpEntity;</p>\n")
#(id: 31, markdown: '<a href="&ouml;&ouml;.html">\n', html: '<a href="&ouml;&ouml;.html">\n')
#(id: 32, markdown: '[foo](/f&ouml;&ouml; "f&ouml;&ouml;")\n', html: '<p><a href="/f%C3%B6%C3%B6" title="f\xc3\xb6\xc3\xb6">foo</a></p>\n')
#(id: 33, markdown: '[foo]\n\n[foo]: /f&ouml;&ouml; "f&ouml;&ouml;"\n', html: '<p><a href="/f%C3%B6%C3%B6" title="f\xc3\xb6\xc3\xb6">foo</a></p>\n')
#(id: 34, markdown: "``` f&ouml;&ouml;\nfoo\n```\n", html: '<pre><code class="language-f\xc3\xb6\xc3\xb6">foo\n</code></pre>\n')
#(id: 35, markdown: "`f&ouml;&ouml;`\n", html: "<p><code>f&amp;ouml;&amp;ouml;</code></p>\n")
#(id: 36, markdown: "    f&ouml;f&ouml;\n", html: "<pre><code>f&amp;ouml;f&amp;ouml;\n</code></pre>\n")
#(id: 37, markdown: "&#42;foo&#42;\n*foo*\n", html: "<p>*foo*\n<em>foo</em></p>\n")
#(id: 38, markdown: "&#42; foo\n\n* foo\n", html: "<p>* foo</p>\n<ul>\n<li>foo</li>\n</ul>\n")
#(id: 39, markdown: "foo&#10;&#10;bar\n", html: "<p>foo\n\nbar</p>\n")
#(id: 40, markdown: "&#9;foo\n", html: "<p>\xe2\x86\x92foo</p>\n")
#(id: 41, markdown: "[a](url &quot;tit&quot;)\n", html: "<p>[a](url &quot;tit&quot;)</p>\n")
#(id: 42, markdown: "- `one\n- two`\n", html: "<ul>\n<li>`one</li>\n<li>two`</li>\n</ul>\n")
#(id: 43, markdown: "***\n---\n___\n", html: "<hr />\n<hr />\n<hr />\n")
#(id: 44, markdown: "+++\n", html: "<p>+++</p>\n")
#(id: 45, markdown: "===\n", html: "<p>===</p>\n")
#(id: 46, markdown: "--\n**\n__\n", html: "<p>--\n**\n__</p>\n")
#(id: 47, markdown: " ***\n  ***\n   ***\n", html: "<hr />\n<hr />\n<hr />\n")
#(id: 48, markdown: "    ***\n", html: "<pre><code>***\n</code></pre>\n")
#(id: 49, markdown: "Foo\n    ***\n", html: "<p>Foo\n***</p>\n")
#(id: 50, markdown: "_____________________________________\n", html: "<hr />\n")
#(id: 51, markdown: " - - -\n", html: "<hr />\n")
#(id: 52, markdown: " **  * ** * ** * **\n", html: "<hr />\n")
#(id: 53, markdown: "-     -      -      -\n", html: "<hr />\n")
#(id: 54, markdown: "- - - -    \n", html: "<hr />\n")
#(id: 55, markdown: "_ _ _ _ a\n\na------\n\n---a---\n", html: "<p>_ _ _ _ a</p>\n<p>a------</p>\n<p>---a---</p>\n")
#(id: 56, markdown: " *-*\n", html: "<p><em>-</em></p>\n")
#(id: 57, markdown: "- foo\n***\n- bar\n", html: "<ul>\n<li>foo</li>\n</ul>\n<hr />\n<ul>\n<li>bar</li>\n</ul>\n")
#(id: 58, markdown: "Foo\n***\nbar\n", html: "<p>Foo</p>\n<hr />\n<p>bar</p>\n")
#(id: 59, markdown: "Foo\n---\nbar\n", html: "<h2>Foo</h2>\n<p>bar</p>\n")
#(id: 60, markdown: "* Foo\n* * *\n* Bar\n", html: "<ul>\n<li>Foo</li>\n</ul>\n<hr />\n<ul>\n<li>Bar</li>\n</ul>\n")
#(id: 61, markdown: "- Foo\n- * * *\n", html: "<ul>\n<li>Foo</li>\n<li>\n<hr />\n</li>\n</ul>\n")
#(id: 62, markdown: "# foo\n## foo\n### foo\n#### foo\n##### foo\n###### foo\n", html: "<h1>foo</h1>\n<h2>foo</h2>\n<h3>foo</h3>\n<h4>foo</h4>\n<h5>foo</h5>\n<h6>foo</h6>\n")
#(id: 63, markdown: "####### foo\n", html: "<p>####### foo</p>\n")
#(id: 64, markdown: "#5 bolt\n\n#hashtag\n", html: "<p>#5 bolt</p>\n<p>#hashtag</p>\n")
#(id: 65, markdown: "\\## foo\n", html: "<p>## foo</p>\n")
#(id: 66, markdown: "# foo *bar* \\*baz\\*\n", html: "<h1>foo <em>bar</em> *baz*</h1>\n")
#(id: 67, markdown: "#                  foo                     \n", html: "<h1>foo</h1>\n")
#(id: 68, markdown: " ### foo\n  ## foo\n   # foo\n", html: "<h3>foo</h3>\n<h2>foo</h2>\n<h1>foo</h1>\n")
#(id: 69, markdown: "    # foo\n", html: "<pre><code># foo\n</code></pre>\n")
#(id: 70, markdown: "foo\n    # bar\n", html: "<p>foo\n# bar</p>\n")
#(id: 71, markdown: "## foo ##\n  ###   bar    ###\n", html: "<h2>foo</h2>\n<h3>bar</h3>\n")
#(id: 72, markdown: "# foo ##################################\n##### foo ##\n", html: "<h1>foo</h1>\n<h5>foo</h5>\n")
#(id: 73, markdown: "### foo ###     \n", html: "<h3>foo</h3>\n")
#(id: 74, markdown: "### foo ### b\n", html: "<h3>foo ### b</h3>\n")
#(id: 75, markdown: "# foo#\n", html: "<h1>foo#</h1>\n")
#(id: 76, markdown: "### foo \\###\n## foo #\\##\n# foo \\#\n", html: "<h3>foo ###</h3>\n<h2>foo ###</h2>\n<h1>foo #</h1>\n")
#(id: 77, markdown: "****\n## foo\n****\n", html: "<hr />\n<h2>foo</h2>\n<hr />\n")
#(id: 78, markdown: "Foo bar\n# baz\nBar foo\n", html: "<p>Foo bar</p>\n<h1>baz</h1>\n<p>Bar foo</p>\n")
#(id: 79, markdown: "## \n#\n### ###\n", html: "<h2></h2>\n<h1></h1>\n<h3></h3>\n")
#(id: 80, markdown: "Foo *bar*\n=========\n\nFoo *bar*\n---------\n", html: "<h1>Foo <em>bar</em></h1>\n<h2>Foo <em>bar</em></h2>\n")
#(id: 81, markdown: "Foo *bar\nbaz*\n====\n", html: "<h1>Foo <em>bar\nbaz</em></h1>\n")
#(id: 82, markdown: "  Foo *bar\nbaz*\t\n====\n", html: "<h1>Foo <em>bar\nbaz</em></h1>\n")
#(id: 83, markdown: "Foo\n-------------------------\n\nFoo\n=\n", html: "<h2>Foo</h2>\n<h1>Foo</h1>\n")
#(id: 84, markdown: "   Foo\n---\n\n  Foo\n-----\n\n  Foo\n  ===\n", html: "<h2>Foo</h2>\n<h2>Foo</h2>\n<h1>Foo</h1>\n")
#(id: 85, markdown: "    Foo\n    ---\n\n    Foo\n---\n", html: "<pre><code>Foo\n---\n\nFoo\n</code></pre>\n<hr />\n")
#(id: 86, markdown: "Foo\n   ----      \n", html: "<h2>Foo</h2>\n")
#(id: 87, markdown: "Foo\n    ---\n", html: "<p>Foo\n---</p>\n")
#(id: 88, markdown: "Foo\n= =\n\nFoo\n--- -\n", html: "<p>Foo\n= =</p>\n<p>Foo</p>\n<hr />\n")
#(id: 89, markdown: "Foo  \n-----\n", html: "<h2>Foo</h2>\n")
#(id: 90, markdown: "Foo\\\n----\n", html: "<h2>Foo\\</h2>\n")
#(id: 91, markdown: '`Foo\n----\n`\n\n<a title="a lot\n---\nof dashes"/>\n', html: "<h2>`Foo</h2>\n<p>`</p>\n<h2>&lt;a title=&quot;a lot</h2>\n<p>of dashes&quot;/&gt;</p>\n")
#(id: 92, markdown: "> Foo\n---\n", html: "<blockquote>\n<p>Foo</p>\n</blockquote>\n<hr />\n")
#(id: 93, markdown: "> foo\nbar\n===\n", html: "<blockquote>\n<p>foo\nbar\n===</p>\n</blockquote>\n")
#(id: 94, markdown: "- Foo\n---\n", html: "<ul>\n<li>Foo</li>\n</ul>\n<hr />\n")
#(id: 95, markdown: "Foo\nBar\n---\n", html: "<h2>Foo\nBar</h2>\n")
#(id: 96, markdown: "---\nFoo\n---\nBar\n---\nBaz\n", html: "<hr />\n<h2>Foo</h2>\n<h2>Bar</h2>\n<p>Baz</p>\n")
#(id: 97, markdown: "\n====\n", html: "<p>====</p>\n")
#(id: 98, markdown: "---\n---\n", html: "<hr />\n<hr />\n")
#(id: 99, markdown: "- foo\n-----\n", html: "<ul>\n<li>foo</li>\n</ul>\n<hr />\n")
#(id: 100, markdown: "    foo\n---\n", html: "<pre><code>foo\n</code></pre>\n<hr />\n")
#(id: 101, markdown: "> foo\n-----\n", html: "<blockquote>\n<p>foo</p>\n</blockquote>\n<hr />\n")
#(id: 102, markdown: "\\> foo\n------\n", html: "<h2>&gt; foo</h2>\n")
#(id: 103, markdown: "Foo\n\nbar\n---\nbaz\n", html: "<p>Foo</p>\n<h2>bar</h2>\n<p>baz</p>\n")
#(id: 104, markdown: "Foo\nbar\n\n---\n\nbaz\n", html: "<p>Foo\nbar</p>\n<hr />\n<p>baz</p>\n")
#(id: 105, markdown: "Foo\nbar\n* * *\nbaz\n", html: "<p>Foo\nbar</p>\n<hr />\n<p>baz</p>\n")
#(id: 106, markdown: "Foo\nbar\n\\---\nbaz\n", html: "<p>Foo\nbar\n---\nbaz</p>\n")
#(id: 107, markdown: "    a simple\n      indented code block\n", html: "<pre><code>a simple\n  indented code block\n</code></pre>\n")
#(id: 108, markdown: "  - foo\n\n    bar\n", html: "<ul>\n<li>\n<p>foo</p>\n<p>bar</p>\n</li>\n</ul>\n")
#(id: 109, markdown: "1.  foo\n\n    - bar\n", html: "<ol>\n<li>\n<p>foo</p>\n<ul>\n<li>bar</li>\n</ul>\n</li>\n</ol>\n")
#(id: 110, markdown: "    <a/>\n    *hi*\n\n    - one\n", html: "<pre><code>&lt;a/&gt;\n*hi*\n\n- one\n</code></pre>\n")
#(id: 111, markdown: "    chunk1\n\n    chunk2\n  \n \n \n    chunk3\n", html: "<pre><code>chunk1\n\nchunk2\n\n\n\nchunk3\n</code></pre>\n")
#(id: 112, markdown: "    chunk1\n      \n      chunk2\n", html: "<pre><code>chunk1\n  \n  chunk2\n</code></pre>\n")
#(id: 113, markdown: "Foo\n    bar\n\n", html: "<p>Foo\nbar</p>\n")
#(id: 114, markdown: "    foo\nbar\n", html: "<pre><code>foo\n</code></pre>\n<p>bar</p>\n")
#(id: 115, markdown: "# Heading\n    foo\nHeading\n------\n    foo\n----\n", html: "<h1>Heading</h1>\n<pre><code>foo\n</code></pre>\n<h2>Heading</h2>\n<pre><code>foo\n</code></pre>\n<hr />\n")
#(id: 116, markdown: "        foo\n    bar\n", html: "<pre><code>    foo\nbar\n</code></pre>\n")
#(id: 117, markdown: "\n    \n    foo\n    \n\n", html: "<pre><code>foo\n</code></pre>\n")
#(id: 118, markdown: "    foo  \n", html: "<pre><code>foo  \n</code></pre>\n")
#(id: 119, markdown: "```\n<\n >\n```\n", html: "<pre><code>&lt;\n &gt;\n</code></pre>\n")
#(id: 120, markdown: "~~~\n<\n >\n~~~\n", html: "<pre><code>&lt;\n &gt;\n</code></pre>\n")
#(id: 121, markdown: "``\nfoo\n``\n", html: "<p><code>foo</code></p>\n")
#(id: 122, markdown: "```\naaa\n~~~\n```\n", html: "<pre><code>aaa\n~~~\n</code></pre>\n")
#(id: 123, markdown: "~~~\naaa\n```\n~~~\n", html: "<pre><code>aaa\n```\n</code></pre>\n")
#(id: 124, markdown: "````\naaa\n```\n``````\n", html: "<pre><code>aaa\n```\n</code></pre>\n")
#(id: 125, markdown: "~~~~\naaa\n~~~\n~~~~\n", html: "<pre><code>aaa\n~~~\n</code></pre>\n")
#(id: 126, markdown: "```\n", html: "<pre><code></code></pre>\n")
#(id: 127, markdown: "`````\n\n```\naaa\n", html: "<pre><code>\n```\naaa\n</code></pre>\n")
#(id: 128, markdown: "> ```\n> aaa\n\nbbb\n", html: "<blockquote>\n<pre><code>aaa\n</code></pre>\n</blockquote>\n<p>bbb</p>\n")
#(id: 129, markdown: "```\n\n  \n```\n", html: "<pre><code>\n  \n</code></pre>\n")
#(id: 130, markdown: "```\n```\n", html: "<pre><code></code></pre>\n")
#(id: 131, markdown: " ```\n aaa\naaa\n```\n", html: "<pre><code>aaa\naaa\n</code></pre>\n")
#(id: 132, markdown: "  ```\naaa\n  aaa\naaa\n  ```\n", html: "<pre><code>aaa\naaa\naaa\n</code></pre>\n")
#(id: 133, markdown: "   ```\n   aaa\n    aaa\n  aaa\n   ```\n", html: "<pre><code>aaa\n aaa\naaa\n</code></pre>\n")
#(id: 134, markdown: "    ```\n    aaa\n    ```\n", html: "<pre><code>```\naaa\n```\n</code></pre>\n")
#(id: 135, markdown: "```\naaa\n  ```\n", html: "<pre><code>aaa\n</code></pre>\n")
#(id: 136, markdown: "   ```\naaa\n  ```\n", html: "<pre><code>aaa\n</code></pre>\n")
#(id: 137, markdown: "```\naaa\n    ```\n", html: "<pre><code>aaa\n    ```\n</code></pre>\n")
#(id: 138, markdown: "``` ```\naaa\n", html: "<p><code> </code>\naaa</p>\n")
#(id: 139, markdown: "~~~~~~\naaa\n~~~ ~~\n", html: "<pre><code>aaa\n~~~ ~~\n</code></pre>\n")
#(id: 140, markdown: "foo\n```\nbar\n```\nbaz\n", html: "<p>foo</p>\n<pre><code>bar\n</code></pre>\n<p>baz</p>\n")
#(id: 141, markdown: "foo\n---\n~~~\nbar\n~~~\n# baz\n", html: "<h2>foo</h2>\n<pre><code>bar\n</code></pre>\n<h1>baz</h1>\n")
#(id: 142, markdown: "```ruby\ndef foo(x)\n  return 3\nend\n```\n", html: '<pre><code class="language-ruby">def foo(x)\n  return 3\nend\n</code></pre>\n')
#(id: 143, markdown: "~~~~    ruby startline=3 $%@#$\ndef foo(x)\n  return 3\nend\n~~~~~~~\n", html: '<pre><code class="language-ruby">def foo(x)\n  return 3\nend\n</code></pre>\n')
#(id: 144, markdown: "````;\n````\n", html: '<pre><code class="language-;"></code></pre>\n')
#(id: 145, markdown: "``` aa ```\nfoo\n", html: "<p><code>aa</code>\nfoo</p>\n")
#(id: 146, markdown: "~~~ aa ``` ~~~\nfoo\n~~~\n", html: '<pre><code class="language-aa">foo\n</code></pre>\n')
#(id: 147, markdown: "```\n``` aaa\n```\n", html: "<pre><code>``` aaa\n</code></pre>\n")
#(id: 148, markdown: "<table><tr><td>\n<pre>\n**Hello**,\n\n_world_.\n</pre>\n</td></tr></table>\n", html: "<table><tr><td>\n<pre>\n**Hello**,\n<p><em>world</em>.\n</pre></p>\n</td></tr></table>\n")
#(id: 149, markdown: "<table>\n  <tr>\n    <td>\n           hi\n    </td>\n  </tr>\n</table>\n\nokay.\n", html: "<table>\n  <tr>\n    <td>\n           hi\n    </td>\n  </tr>\n</table>\n<p>okay.</p>\n")
#(id: 150, markdown: " <div>\n  *hello*\n         <foo><a>\n", html: " <div>\n  *hello*\n         <foo><a>\n")
#(id: 151, markdown: "</div>\n*foo*\n", html: "</div>\n*foo*\n")
#(id: 152, markdown: '<DIV CLASS="foo">\n\n*Markdown*\n\n</DIV>\n', html: '<DIV CLASS="foo">\n<p><em>Markdown</em></p>\n</DIV>\n')
#(id: 153, markdown: '<div id="foo"\n  class="bar">\n</div>\n', html: '<div id="foo"\n  class="bar">\n</div>\n')
#(id: 154, markdown: '<div id="foo" class="bar\n  baz">\n</div>\n', html: '<div id="foo" class="bar\n  baz">\n</div>\n')
#(id: 155, markdown: "<div>\n*foo*\n\n*bar*\n", html: "<div>\n*foo*\n<p><em>bar</em></p>\n")
#(id: 156, markdown: '<div id="foo"\n*hi*\n', html: '<div id="foo"\n*hi*\n')
#(id: 157, markdown: "<div class\nfoo\n", html: "<div class\nfoo\n")
#(id: 158, markdown: "<div *???-&&&-<---\n*foo*\n", html: "<div *???-&&&-<---\n*foo*\n")
#(id: 159, markdown: '<div><a href="bar">*foo*</a></div>\n', html: '<div><a href="bar">*foo*</a></div>\n')
#(id: 160, markdown: "<table><tr><td>\nfoo\n</td></tr></table>\n", html: "<table><tr><td>\nfoo\n</td></tr></table>\n")
#(id: 161, markdown: "<div></div>\n``` c\nint x = 33;\n```\n", html: "<div></div>\n``` c\nint x = 33;\n```\n")
#(id: 162, markdown: '<a href="foo">\n*bar*\n</a>\n', html: '<a href="foo">\n*bar*\n</a>\n')
#(id: 163, markdown: "<Warning>\n*bar*\n</Warning>\n", html: "<Warning>\n*bar*\n</Warning>\n")
#(id: 164, markdown: '<i class="foo">\n*bar*\n</i>\n', html: '<i class="foo">\n*bar*\n</i>\n')
#(id: 165, markdown: "</ins>\n*bar*\n", html: "</ins>\n*bar*\n")
#(id: 166, markdown: "<del>\n*foo*\n</del>\n", html: "<del>\n*foo*\n</del>\n")
#(id: 167, markdown: "<del>\n\n*foo*\n\n</del>\n", html: "<del>\n<p><em>foo</em></p>\n</del>\n")
#(id: 168, markdown: "<del>*foo*</del>\n", html: "<p><del><em>foo</em></del></p>\n")
#(id: 169, markdown: '<pre language="haskell"><code>\nimport Text.HTML.TagSoup\n\nmain :: IO ()\nmain = print $ parseTags tags\n</code></pre>\nokay\n', html: '<pre language="haskell"><code>\nimport Text.HTML.TagSoup\n\nmain :: IO ()\nmain = print $ parseTags tags\n</code></pre>\n<p>okay</p>\n')
#(id: 170, markdown: '<script type="text/javascript">\n// JavaScript example\n\ndocument.getElementById("demo").innerHTML = "Hello JavaScript!";\n</script>\nokay\n', html: '<script type="text/javascript">\n// JavaScript example\n\ndocument.getElementById("demo").innerHTML = "Hello JavaScript!";\n</script>\n<p>okay</p>\n')
#(id: 171, markdown: "<textarea>\n\n*foo*\n\n_bar_\n\n</textarea>\n", html: "<textarea>\n\n*foo*\n\n_bar_\n\n</textarea>\n")
#(id: 172, markdown: '<style\n  type="text/css">\nh1 {color:red;}\n\np {color:blue;}\n</style>\nokay\n', html: '<style\n  type="text/css">\nh1 {color:red;}\n\np {color:blue;}\n</style>\n<p>okay</p>\n')
#(id: 173, markdown: '<style\n  type="text/css">\n\nfoo\n', html: '<style\n  type="text/css">\n\nfoo\n')
#(id: 174, markdown: "> <div>\n> foo\n\nbar\n", html: "<blockquote>\n<div>\nfoo\n</blockquote>\n<p>bar</p>\n")
#(id: 175, markdown: "- <div>\n- foo\n", html: "<ul>\n<li>\n<div>\n</li>\n<li>foo</li>\n</ul>\n")
#(id: 176, markdown: "<style>p{color:red;}</style>\n*foo*\n", html: "<style>p{color:red;}</style>\n<p><em>foo</em></p>\n")
#(id: 177, markdown: "<!-- foo -->*bar*\n*baz*\n", html: "<!-- foo -->*bar*\n<p><em>baz</em></p>\n")
#(id: 178, markdown: "<script>\nfoo\n</script>1. *bar*\n", html: "<script>\nfoo\n</script>1. *bar*\n")
#(id: 179, markdown: "<!-- Foo\n\nbar\n   baz -->\nokay\n", html: "<!-- Foo\n\nbar\n   baz -->\n<p>okay</p>\n")
#(id: 180, markdown: "<?php\n\n  echo '>';\n\n?>\nokay\n", html: "<?php\n\n  echo '>';\n\n?>\n<p>okay</p>\n")
#(id: 181, markdown: "<!DOCTYPE html>\n", html: "<!DOCTYPE html>\n")
#(id: 182, markdown: "<![CDATA[\nfunction matchwo(a,b)\n{\n  if (a < b && a < 0) then {\n    return 1;\n\n  } else {\n\n    return 0;\n  }\n}\n]]>\nokay\n", html: "<![CDATA[\nfunction matchwo(a,b)\n{\n  if (a < b && a < 0) then {\n    return 1;\n\n  } else {\n\n    return 0;\n  }\n}\n]]>\n<p>okay</p>\n")
#(id: 183, markdown: "  <!-- foo -->\n\n    <!-- foo -->\n", html: "  <!-- foo -->\n<pre><code>&lt;!-- foo --&gt;\n</code></pre>\n")
#(id: 184, markdown: "  <div>\n\n    <div>\n", html: "  <div>\n<pre><code>&lt;div&gt;\n</code></pre>\n")
#(id: 185, markdown: "Foo\n<div>\nbar\n</div>\n", html: "<p>Foo</p>\n<div>\nbar\n</div>\n")
#(id: 186, markdown: "<div>\nbar\n</div>\n*foo*\n", html: "<div>\nbar\n</div>\n*foo*\n")
#(id: 187, markdown: 'Foo\n<a href="bar">\nbaz\n', html: '<p>Foo\n<a href="bar">\nbaz</p>\n')
#(id: 188, markdown: "<div>\n\n*Emphasized* text.\n\n</div>\n", html: "<div>\n<p><em>Emphasized</em> text.</p>\n</div>\n")
#(id: 189, markdown: "<div>\n*Emphasized* text.\n</div>\n", html: "<div>\n*Emphasized* text.\n</div>\n")
#(id: 190, markdown: "<table>\n\n<tr>\n\n<td>\nHi\n</td>\n\n</tr>\n\n</table>\n", html: "<table>\n<tr>\n<td>\nHi\n</td>\n</tr>\n</table>\n")
#(id: 191, markdown: "<table>\n\n  <tr>\n\n    <td>\n      Hi\n    </td>\n\n  </tr>\n\n</table>\n", html: "<table>\n  <tr>\n<pre><code>&lt;td&gt;\n  Hi\n&lt;/td&gt;\n</code></pre>\n  </tr>\n</table>\n")
#(id: 192, markdown: '[foo]: /url "title"\n\n[foo]\n', html: '<p><a href="/url" title="title">foo</a></p>\n')
#(id: 193, markdown: "   [foo]: \n      /url  \n           'the title'  \n\n[foo]\n", html: '<p><a href="/url" title="the title">foo</a></p>\n')
#(id: 194, markdown: "[Foo*bar\\]]:my_(url) 'title (with parens)'\n\n[Foo*bar\\]]\n", html: '<p><a href="my_(url)" title="title (with parens)">Foo*bar]</a></p>\n')
#(id: 195, markdown: "[Foo bar]:\n<my url>\n'title'\n\n[Foo bar]\n", html: '<p><a href="my%20url" title="title">Foo bar</a></p>\n')
#(id: 196, markdown: "[foo]: /url '\ntitle\nline1\nline2\n'\n\n[foo]\n", html: '<p><a href="/url" title="\ntitle\nline1\nline2\n">foo</a></p>\n')
#(id: 197, markdown: "[foo]: /url 'title\n\nwith blank line'\n\n[foo]\n", html: "<p>[foo]: /url 'title</p>\n<p>with blank line'</p>\n<p>[foo]</p>\n")
#(id: 198, markdown: "[foo]:\n/url\n\n[foo]\n", html: '<p><a href="/url">foo</a></p>\n')
#(id: 199, markdown: "[foo]:\n\n[foo]\n", html: "<p>[foo]:</p>\n<p>[foo]</p>\n")
#(id: 200, markdown: "[foo]: <>\n\n[foo]\n", html: '<p><a href="">foo</a></p>\n')
#(id: 201, markdown: "[foo]: <bar>(baz)\n\n[foo]\n", html: "<p>[foo]: <bar>(baz)</p>\n<p>[foo]</p>\n")
#(id: 202, markdown: '[foo]: /url\\bar\\*baz "foo\\"bar\\baz"\n\n[foo]\n', html: '<p><a href="/url%5Cbar*baz" title="foo&quot;bar\\baz">foo</a></p>\n')
#(id: 203, markdown: "[foo]\n\n[foo]: url\n", html: '<p><a href="url">foo</a></p>\n')
#(id: 204, markdown: "[foo]\n\n[foo]: first\n[foo]: second\n", html: '<p><a href="first">foo</a></p>\n')
#(id: 205, markdown: "[FOO]: /url\n\n[Foo]\n", html: '<p><a href="/url">Foo</a></p>\n')
#(id: 206, markdown: "[\xce\x91\xce\x93\xce\xa9]: /\xcf\x86\xce\xbf\xcf\x85\n\n[\xce\xb1\xce\xb3\xcf\x89]\n", html: '<p><a href="/%CF%86%CE%BF%CF%85">\xce\xb1\xce\xb3\xcf\x89</a></p>\n')
#(id: 207, markdown: "[foo]: /url\n", html: "")
#(id: 208, markdown: "[\nfoo\n]: /url\nbar\n", html: "<p>bar</p>\n")
#(id: 209, markdown: '[foo]: /url "title" ok\n', html: "<p>[foo]: /url &quot;title&quot; ok</p>\n")
#(id: 210, markdown: '[foo]: /url\n"title" ok\n', html: "<p>&quot;title&quot; ok</p>\n")
#(id: 211, markdown: '    [foo]: /url "title"\n\n[foo]\n', html: "<pre><code>[foo]: /url &quot;title&quot;\n</code></pre>\n<p>[foo]</p>\n")
#(id: 212, markdown: "```\n[foo]: /url\n```\n\n[foo]\n", html: "<pre><code>[foo]: /url\n</code></pre>\n<p>[foo]</p>\n")
#(id: 213, markdown: "Foo\n[bar]: /baz\n\n[bar]\n", html: "<p>Foo\n[bar]: /baz</p>\n<p>[bar]</p>\n")
#(id: 214, markdown: "# [Foo]\n[foo]: /url\n> bar\n", html: '<h1><a href="/url">Foo</a></h1>\n<blockquote>\n<p>bar</p>\n</blockquote>\n')
#(id: 215, markdown: "[foo]: /url\nbar\n===\n[foo]\n", html: '<h1>bar</h1>\n<p><a href="/url">foo</a></p>\n')
#(id: 216, markdown: "[foo]: /url\n===\n[foo]\n", html: '<p>===\n<a href="/url">foo</a></p>\n')
#(id: 217, markdown: '[foo]: /foo-url "foo"\n[bar]: /bar-url\n  "bar"\n[baz]: /baz-url\n\n[foo],\n[bar],\n[baz]\n', html: '<p><a href="/foo-url" title="foo">foo</a>,\n<a href="/bar-url" title="bar">bar</a>,\n<a href="/baz-url">baz</a></p>\n')
#(id: 218, markdown: "[foo]\n\n> [foo]: /url\n", html: '<p><a href="/url">foo</a></p>\n<blockquote>\n</blockquote>\n')
#(id: 219, markdown: "aaa\n\nbbb\n", html: "<p>aaa</p>\n<p>bbb</p>\n")
#(id: 220, markdown: "aaa\nbbb\n\nccc\nddd\n", html: "<p>aaa\nbbb</p>\n<p>ccc\nddd</p>\n")
#(id: 221, markdown: "aaa\n\n\nbbb\n", html: "<p>aaa</p>\n<p>bbb</p>\n")
#(id: 222, markdown: "  aaa\n bbb\n", html: "<p>aaa\nbbb</p>\n")
#(id: 223, markdown: "aaa\n             bbb\n                                       ccc\n", html: "<p>aaa\nbbb\nccc</p>\n")
#(id: 224, markdown: "   aaa\nbbb\n", html: "<p>aaa\nbbb</p>\n")
#(id: 225, markdown: "    aaa\nbbb\n", html: "<pre><code>aaa\n</code></pre>\n<p>bbb</p>\n")
#(id: 226, markdown: "aaa     \nbbb     \n", html: "<p>aaa<br />\nbbb</p>\n")
#(id: 227, markdown: "  \n\naaa\n  \n\n# aaa\n\n  \n", html: "<p>aaa</p>\n<h1>aaa</h1>\n")
#(id: 228, markdown: "> # Foo\n> bar\n> baz\n", html: "<blockquote>\n<h1>Foo</h1>\n<p>bar\nbaz</p>\n</blockquote>\n")
#(id: 229, markdown: "># Foo\n>bar\n> baz\n", html: "<blockquote>\n<h1>Foo</h1>\n<p>bar\nbaz</p>\n</blockquote>\n")
#(id: 230, markdown: "   > # Foo\n   > bar\n > baz\n", html: "<blockquote>\n<h1>Foo</h1>\n<p>bar\nbaz</p>\n</blockquote>\n")
#(id: 231, markdown: "    > # Foo\n    > bar\n    > baz\n", html: "<pre><code>&gt; # Foo\n&gt; bar\n&gt; baz\n</code></pre>\n")
#(id: 232, markdown: "> # Foo\n> bar\nbaz\n", html: "<blockquote>\n<h1>Foo</h1>\n<p>bar\nbaz</p>\n</blockquote>\n")
#(id: 233, markdown: "> bar\nbaz\n> foo\n", html: "<blockquote>\n<p>bar\nbaz\nfoo</p>\n</blockquote>\n")
#(id: 234, markdown: "> foo\n---\n", html: "<blockquote>\n<p>foo</p>\n</blockquote>\n<hr />\n")
#(id: 235, markdown: "> - foo\n- bar\n", html: "<blockquote>\n<ul>\n<li>foo</li>\n</ul>\n</blockquote>\n<ul>\n<li>bar</li>\n</ul>\n")
#(id: 236, markdown: ">     foo\n    bar\n", html: "<blockquote>\n<pre><code>foo\n</code></pre>\n</blockquote>\n<pre><code>bar\n</code></pre>\n")
#(id: 237, markdown: "> ```\nfoo\n```\n", html: "<blockquote>\n<pre><code></code></pre>\n</blockquote>\n<p>foo</p>\n<pre><code></code></pre>\n")
#(id: 238, markdown: "> foo\n    - bar\n", html: "<blockquote>\n<p>foo\n- bar</p>\n</blockquote>\n")
#(id: 239, markdown: ">\n", html: "<blockquote>\n</blockquote>\n")
#(id: 240, markdown: ">\n>  \n> \n", html: "<blockquote>\n</blockquote>\n")
#(id: 241, markdown: ">\n> foo\n>  \n", html: "<blockquote>\n<p>foo</p>\n</blockquote>\n")
#(id: 242, markdown: "> foo\n\n> bar\n", html: "<blockquote>\n<p>foo</p>\n</blockquote>\n<blockquote>\n<p>bar</p>\n</blockquote>\n")
#(id: 243, markdown: "> foo\n> bar\n", html: "<blockquote>\n<p>foo\nbar</p>\n</blockquote>\n")
#(id: 244, markdown: "> foo\n>\n> bar\n", html: "<blockquote>\n<p>foo</p>\n<p>bar</p>\n</blockquote>\n")
#(id: 245, markdown: "foo\n> bar\n", html: "<p>foo</p>\n<blockquote>\n<p>bar</p>\n</blockquote>\n")
#(id: 246, markdown: "> aaa\n***\n> bbb\n", html: "<blockquote>\n<p>aaa</p>\n</blockquote>\n<hr />\n<blockquote>\n<p>bbb</p>\n</blockquote>\n")
#(id: 247, markdown: "> bar\nbaz\n", html: "<blockquote>\n<p>bar\nbaz</p>\n</blockquote>\n")
#(id: 248, markdown: "> bar\n\nbaz\n", html: "<blockquote>\n<p>bar</p>\n</blockquote>\n<p>baz</p>\n")
#(id: 249, markdown: "> bar\n>\nbaz\n", html: "<blockquote>\n<p>bar</p>\n</blockquote>\n<p>baz</p>\n")
#(id: 250, markdown: "> > > foo\nbar\n", html: "<blockquote>\n<blockquote>\n<blockquote>\n<p>foo\nbar</p>\n</blockquote>\n</blockquote>\n</blockquote>\n")
#(id: 251, markdown: ">>> foo\n> bar\n>>baz\n", html: "<blockquote>\n<blockquote>\n<blockquote>\n<p>foo\nbar\nbaz</p>\n</blockquote>\n</blockquote>\n</blockquote>\n")
#(id: 252, markdown: ">     code\n\n>    not code\n", html: "<blockquote>\n<pre><code>code\n</code></pre>\n</blockquote>\n<blockquote>\n<p>not code</p>\n</blockquote>\n")
#(id: 253, markdown: "A paragraph\nwith two lines.\n\n    indented code\n\n> A block quote.\n", html: "<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n")
#(id: 254, markdown: "1.  A paragraph\n    with two lines.\n\n        indented code\n\n    > A block quote.\n", html: "<ol>\n<li>\n<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n</li>\n</ol>\n")
#(id: 255, markdown: "- one\n\n two\n", html: "<ul>\n<li>one</li>\n</ul>\n<p>two</p>\n")
#(id: 256, markdown: "- one\n\n  two\n", html: "<ul>\n<li>\n<p>one</p>\n<p>two</p>\n</li>\n</ul>\n")
#(id: 257, markdown: " -    one\n\n     two\n", html: "<ul>\n<li>one</li>\n</ul>\n<pre><code> two\n</code></pre>\n")
#(id: 258, markdown: " -    one\n\n      two\n", html: "<ul>\n<li>\n<p>one</p>\n<p>two</p>\n</li>\n</ul>\n")
#(id: 259, markdown: "   > > 1.  one\n>>\n>>     two\n", html: "<blockquote>\n<blockquote>\n<ol>\n<li>\n<p>one</p>\n<p>two</p>\n</li>\n</ol>\n</blockquote>\n</blockquote>\n")
#(id: 260, markdown: ">>- one\n>>\n  >  > two\n", html: "<blockquote>\n<blockquote>\n<ul>\n<li>one</li>\n</ul>\n<p>two</p>\n</blockquote>\n</blockquote>\n")
#(id: 261, markdown: "-one\n\n2.two\n", html: "<p>-one</p>\n<p>2.two</p>\n")
#(id: 262, markdown: "- foo\n\n\n  bar\n", html: "<ul>\n<li>\n<p>foo</p>\n<p>bar</p>\n</li>\n</ul>\n")
#(id: 263, markdown: "1.  foo\n\n    ```\n    bar\n    ```\n\n    baz\n\n    > bam\n", html: "<ol>\n<li>\n<p>foo</p>\n<pre><code>bar\n</code></pre>\n<p>baz</p>\n<blockquote>\n<p>bam</p>\n</blockquote>\n</li>\n</ol>\n")
#(id: 264, markdown: "- Foo\n\n      bar\n\n\n      baz\n", html: "<ul>\n<li>\n<p>Foo</p>\n<pre><code>bar\n\n\nbaz\n</code></pre>\n</li>\n</ul>\n")
#(id: 265, markdown: "123456789. ok\n", html: '<ol start="123456789">\n<li>ok</li>\n</ol>\n')
#(id: 266, markdown: "1234567890. not ok\n", html: "<p>1234567890. not ok</p>\n")
#(id: 267, markdown: "0. ok\n", html: '<ol start="0">\n<li>ok</li>\n</ol>\n')
#(id: 268, markdown: "003. ok\n", html: '<ol start="3">\n<li>ok</li>\n</ol>\n')
#(id: 269, markdown: "-1. not ok\n", html: "<p>-1. not ok</p>\n")
#(id: 270, markdown: "- foo\n\n      bar\n", html: "<ul>\n<li>\n<p>foo</p>\n<pre><code>bar\n</code></pre>\n</li>\n</ul>\n")
#(id: 271, markdown: "  10.  foo\n\n           bar\n", html: '<ol start="10">\n<li>\n<p>foo</p>\n<pre><code>bar\n</code></pre>\n</li>\n</ol>\n')
#(id: 272, markdown: "    indented code\n\nparagraph\n\n    more code\n", html: "<pre><code>indented code\n</code></pre>\n<p>paragraph</p>\n<pre><code>more code\n</code></pre>\n")
#(id: 273, markdown: "1.     indented code\n\n   paragraph\n\n       more code\n", html: "<ol>\n<li>\n<pre><code>indented code\n</code></pre>\n<p>paragraph</p>\n<pre><code>more code\n</code></pre>\n</li>\n</ol>\n")
#(id: 274, markdown: "1.      indented code\n\n   paragraph\n\n       more code\n", html: "<ol>\n<li>\n<pre><code> indented code\n</code></pre>\n<p>paragraph</p>\n<pre><code>more code\n</code></pre>\n</li>\n</ol>\n")
#(id: 275, markdown: "   foo\n\nbar\n", html: "<p>foo</p>\n<p>bar</p>\n")
#(id: 276, markdown: "-    foo\n\n  bar\n", html: "<ul>\n<li>foo</li>\n</ul>\n<p>bar</p>\n")
#(id: 277, markdown: "-  foo\n\n   bar\n", html: "<ul>\n<li>\n<p>foo</p>\n<p>bar</p>\n</li>\n</ul>\n")
#(id: 278, markdown: "-\n  foo\n-\n  ```\n  bar\n  ```\n-\n      baz\n", html: "<ul>\n<li>foo</li>\n<li>\n<pre><code>bar\n</code></pre>\n</li>\n<li>\n<pre><code>baz\n</code></pre>\n</li>\n</ul>\n")
#(id: 279, markdown: "-   \n  foo\n", html: "<ul>\n<li>foo</li>\n</ul>\n")
#(id: 280, markdown: "-\n\n  foo\n", html: "<ul>\n<li></li>\n</ul>\n<p>foo</p>\n")
#(id: 281, markdown: "- foo\n-\n- bar\n", html: "<ul>\n<li>foo</li>\n<li></li>\n<li>bar</li>\n</ul>\n")
#(id: 282, markdown: "- foo\n-   \n- bar\n", html: "<ul>\n<li>foo</li>\n<li></li>\n<li>bar</li>\n</ul>\n")
#(id: 283, markdown: "1. foo\n2.\n3. bar\n", html: "<ol>\n<li>foo</li>\n<li></li>\n<li>bar</li>\n</ol>\n")
#(id: 284, markdown: "*\n", html: "<ul>\n<li></li>\n</ul>\n")
#(id: 285, markdown: "foo\n*\n\nfoo\n1.\n", html: "<p>foo\n*</p>\n<p>foo\n1.</p>\n")
#(id: 286, markdown: " 1.  A paragraph\n     with two lines.\n\n         indented code\n\n     > A block quote.\n", html: "<ol>\n<li>\n<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n</li>\n</ol>\n")
#(id: 287, markdown: "  1.  A paragraph\n      with two lines.\n\n          indented code\n\n      > A block quote.\n", html: "<ol>\n<li>\n<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n</li>\n</ol>\n")
#(id: 288, markdown: "   1.  A paragraph\n       with two lines.\n\n           indented code\n\n       > A block quote.\n", html: "<ol>\n<li>\n<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n</li>\n</ol>\n")
#(id: 289, markdown: "    1.  A paragraph\n        with two lines.\n\n            indented code\n\n        > A block quote.\n", html: "<pre><code>1.  A paragraph\n    with two lines.\n\n        indented code\n\n    &gt; A block quote.\n</code></pre>\n")
#(id: 290, markdown: "  1.  A paragraph\nwith two lines.\n\n          indented code\n\n      > A block quote.\n", html: "<ol>\n<li>\n<p>A paragraph\nwith two lines.</p>\n<pre><code>indented code\n</code></pre>\n<blockquote>\n<p>A block quote.</p>\n</blockquote>\n</li>\n</ol>\n")
#(id: 291, markdown: "  1.  A paragraph\n    with two lines.\n", html: "<ol>\n<li>A paragraph\nwith two lines.</li>\n</ol>\n")
#(id: 292, markdown: "> 1. > Blockquote\ncontinued here.\n", html: "<blockquote>\n<ol>\n<li>\n<blockquote>\n<p>Blockquote\ncontinued here.</p>\n</blockquote>\n</li>\n</ol>\n</blockquote>\n")
#(id: 293, markdown: "> 1. > Blockquote\n> continued here.\n", html: "<blockquote>\n<ol>\n<li>\n<blockquote>\n<p>Blockquote\ncontinued here.</p>\n</blockquote>\n</li>\n</ol>\n</blockquote>\n")
#(id: 294, markdown: "- foo\n  - bar\n    - baz\n      - boo\n", html: "<ul>\n<li>foo\n<ul>\n<li>bar\n<ul>\n<li>baz\n<ul>\n<li>boo</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n")
#(id: 295, markdown: "- foo\n - bar\n  - baz\n   - boo\n", html: "<ul>\n<li>foo</li>\n<li>bar</li>\n<li>baz</li>\n<li>boo</li>\n</ul>\n")
#(id: 296, markdown: "10) foo\n    - bar\n", html: '<ol start="10">\n<li>foo\n<ul>\n<li>bar</li>\n</ul>\n</li>\n</ol>\n')
#(id: 297, markdown: "10) foo\n   - bar\n", html: '<ol start="10">\n<li>foo</li>\n</ol>\n<ul>\n<li>bar</li>\n</ul>\n')
#(id: 298, markdown: "- - foo\n", html: "<ul>\n<li>\n<ul>\n<li>foo</li>\n</ul>\n</li>\n</ul>\n")
#(id: 299, markdown: "1. - 2. foo\n", html: '<ol>\n<li>\n<ul>\n<li>\n<ol start="2">\n<li>foo</li>\n</ol>\n</li>\n</ul>\n</li>\n</ol>\n')
#(id: 300, markdown: "- # Foo\n- Bar\n  ---\n  baz\n", html: "<ul>\n<li>\n<h1>Foo</h1>\n</li>\n<li>\n<h2>Bar</h2>\nbaz</li>\n</ul>\n")
#(id: 301, markdown: "- foo\n- bar\n+ baz\n", html: "<ul>\n<li>foo</li>\n<li>bar</li>\n</ul>\n<ul>\n<li>baz</li>\n</ul>\n")
#(id: 302, markdown: "1. foo\n2. bar\n3) baz\n", html: '<ol>\n<li>foo</li>\n<li>bar</li>\n</ol>\n<ol start="3">\n<li>baz</li>\n</ol>\n')
#(id: 303, markdown: "Foo\n- bar\n- baz\n", html: "<p>Foo</p>\n<ul>\n<li>bar</li>\n<li>baz</li>\n</ul>\n")
#(id: 304, markdown: "The number of windows in my house is\n14.  The number of doors is 6.\n", html: "<p>The number of windows in my house is\n14.  The number of doors is 6.</p>\n")
#(id: 305, markdown: "The number of windows in my house is\n1.  The number of doors is 6.\n", html: "<p>The number of windows in my house is</p>\n<ol>\n<li>The number of doors is 6.</li>\n</ol>\n")
#(id: 306, markdown: "- foo\n\n- bar\n\n\n- baz\n", html: "<ul>\n<li>\n<p>foo</p>\n</li>\n<li>\n<p>bar</p>\n</li>\n<li>\n<p>baz</p>\n</li>\n</ul>\n")
#(id: 307, markdown: "- foo\n  - bar\n    - baz\n\n\n      bim\n", html: "<ul>\n<li>foo\n<ul>\n<li>bar\n<ul>\n<li>\n<p>baz</p>\n<p>bim</p>\n</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n")
#(id: 308, markdown: "- foo\n- bar\n\n<!-- -->\n\n- baz\n- bim\n", html: "<ul>\n<li>foo</li>\n<li>bar</li>\n</ul>\n<!-- -->\n<ul>\n<li>baz</li>\n<li>bim</li>\n</ul>\n")
#(id: 309, markdown: "-   foo\n\n    notcode\n\n-   foo\n\n<!-- -->\n\n    code\n", html: "<ul>\n<li>\n<p>foo</p>\n<p>notcode</p>\n</li>\n<li>\n<p>foo</p>\n</li>\n</ul>\n<!-- -->\n<pre><code>code\n</code></pre>\n")
#(id: 310, markdown: "- a\n - b\n  - c\n   - d\n  - e\n - f\n- g\n", html: "<ul>\n<li>a</li>\n<li>b</li>\n<li>c</li>\n<li>d</li>\n<li>e</li>\n<li>f</li>\n<li>g</li>\n</ul>\n")
#(id: 311, markdown: "1. a\n\n  2. b\n\n   3. c\n", html: "<ol>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n</li>\n<li>\n<p>c</p>\n</li>\n</ol>\n")
#(id: 312, markdown: "- a\n - b\n  - c\n   - d\n    - e\n", html: "<ul>\n<li>a</li>\n<li>b</li>\n<li>c</li>\n<li>d\n- e</li>\n</ul>\n")
#(id: 313, markdown: "1. a\n\n  2. b\n\n    3. c\n", html: "<ol>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n</li>\n</ol>\n<pre><code>3. c\n</code></pre>\n")
#(id: 314, markdown: "- a\n- b\n\n- c\n", html: "<ul>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n</li>\n<li>\n<p>c</p>\n</li>\n</ul>\n")
#(id: 315, markdown: "* a\n*\n\n* c\n", html: "<ul>\n<li>\n<p>a</p>\n</li>\n<li></li>\n<li>\n<p>c</p>\n</li>\n</ul>\n")
#(id: 316, markdown: "- a\n- b\n\n  c\n- d\n", html: "<ul>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n<p>c</p>\n</li>\n<li>\n<p>d</p>\n</li>\n</ul>\n")
#(id: 317, markdown: "- a\n- b\n\n  [ref]: /url\n- d\n", html: "<ul>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n</li>\n<li>\n<p>d</p>\n</li>\n</ul>\n")
#(id: 318, markdown: "- a\n- ```\n  b\n\n\n  ```\n- c\n", html: "<ul>\n<li>a</li>\n<li>\n<pre><code>b\n\n\n</code></pre>\n</li>\n<li>c</li>\n</ul>\n")
#(id: 319, markdown: "- a\n  - b\n\n    c\n- d\n", html: "<ul>\n<li>a\n<ul>\n<li>\n<p>b</p>\n<p>c</p>\n</li>\n</ul>\n</li>\n<li>d</li>\n</ul>\n")
#(id: 320, markdown: "* a\n  > b\n  >\n* c\n", html: "<ul>\n<li>a\n<blockquote>\n<p>b</p>\n</blockquote>\n</li>\n<li>c</li>\n</ul>\n")
#(id: 321, markdown: "- a\n  > b\n  ```\n  c\n  ```\n- d\n", html: "<ul>\n<li>a\n<blockquote>\n<p>b</p>\n</blockquote>\n<pre><code>c\n</code></pre>\n</li>\n<li>d</li>\n</ul>\n")
#(id: 322, markdown: "- a\n", html: "<ul>\n<li>a</li>\n</ul>\n")
#(id: 323, markdown: "- a\n  - b\n", html: "<ul>\n<li>a\n<ul>\n<li>b</li>\n</ul>\n</li>\n</ul>\n")
#(id: 324, markdown: "1. ```\n   foo\n   ```\n\n   bar\n", html: "<ol>\n<li>\n<pre><code>foo\n</code></pre>\n<p>bar</p>\n</li>\n</ol>\n")
#(id: 325, markdown: "* foo\n  * bar\n\n  baz\n", html: "<ul>\n<li>\n<p>foo</p>\n<ul>\n<li>bar</li>\n</ul>\n<p>baz</p>\n</li>\n</ul>\n")
#(id: 326, markdown: "- a\n  - b\n  - c\n\n- d\n  - e\n  - f\n", html: "<ul>\n<li>\n<p>a</p>\n<ul>\n<li>b</li>\n<li>c</li>\n</ul>\n</li>\n<li>\n<p>d</p>\n<ul>\n<li>e</li>\n<li>f</li>\n</ul>\n</li>\n</ul>\n")
#(id: 327, markdown: "`hi`lo`\n", html: "<p><code>hi</code>lo`</p>\n")
#(id: 328, markdown: "`foo`\n", html: "<p><code>foo</code></p>\n")
#(id: 329, markdown: "`` foo ` bar ``\n", html: "<p><code>foo ` bar</code></p>\n")
#(id: 330, markdown: "` `` `\n", html: "<p><code>``</code></p>\n")
#(id: 331, markdown: "`  ``  `\n", html: "<p><code> `` </code></p>\n")
#(id: 332, markdown: "` a`\n", html: "<p><code> a</code></p>\n")
#(id: 333, markdown: "`\xc2\xa0b\xc2\xa0`\n", html: "<p><code>\xc2\xa0b\xc2\xa0</code></p>\n")
#(id: 334, markdown: "`\xc2\xa0`\n`  `\n", html: "<p><code>\xc2\xa0</code>\n<code>  </code></p>\n")
#(id: 335, markdown: "``\nfoo\nbar  \nbaz\n``\n", html: "<p><code>foo bar   baz</code></p>\n")
#(id: 336, markdown: "``\nfoo \n``\n", html: "<p><code>foo </code></p>\n")
#(id: 337, markdown: "`foo   bar \nbaz`\n", html: "<p><code>foo   bar  baz</code></p>\n")
#(id: 338, markdown: "`foo\\`bar`\n", html: "<p><code>foo\\</code>bar`</p>\n")
#(id: 339, markdown: "``foo`bar``\n", html: "<p><code>foo`bar</code></p>\n")
#(id: 340, markdown: "` foo `` bar `\n", html: "<p><code>foo `` bar</code></p>\n")
#(id: 341, markdown: "*foo`*`\n", html: "<p>*foo<code>*</code></p>\n")
#(id: 342, markdown: "[not a `link](/foo`)\n", html: "<p>[not a <code>link](/foo</code>)</p>\n")
#(id: 343, markdown: '`<a href="`">`\n', html: "<p><code>&lt;a href=&quot;</code>&quot;&gt;`</p>\n")
#(id: 344, markdown: '<a href="`">`\n', html: '<p><a href="`">`</p>\n')
#(id: 345, markdown: "`<https://foo.bar.`baz>`\n", html: "<p><code>&lt;https://foo.bar.</code>baz&gt;`</p>\n")
#(id: 346, markdown: "<https://foo.bar.`baz>`\n", html: '<p><a href="https://foo.bar.%60baz">https://foo.bar.`baz</a>`</p>\n')
#(id: 347, markdown: "```foo``\n", html: "<p>```foo``</p>\n")
#(id: 348, markdown: "`foo\n", html: "<p>`foo</p>\n")
#(id: 349, markdown: "`foo``bar``\n", html: "<p>`foo<code>bar</code></p>\n")
#(id: 350, markdown: "*foo bar*\n", html: "<p><em>foo bar</em></p>\n")
#(id: 351, markdown: "a * foo bar*\n", html: "<p>a * foo bar*</p>\n")
#(id: 352, markdown: 'a*"foo"*\n', html: "<p>a*&quot;foo&quot;*</p>\n")
#(id: 353, markdown: "*\xc2\xa0a\xc2\xa0*\n", html: "<p>*\xc2\xa0a\xc2\xa0*</p>\n")
#(id: 354, markdown: "*$*alpha.\n\n*\xc2\xa3*bravo.\n\n*\xe2\x82\xac*charlie.\n", html: "<p>*$*alpha.</p>\n<p>*\xc2\xa3*bravo.</p>\n<p>*\xe2\x82\xac*charlie.</p>\n")
#(id: 355, markdown: "foo*bar*\n", html: "<p>foo<em>bar</em></p>\n")
#(id: 356, markdown: "5*6*78\n", html: "<p>5<em>6</em>78</p>\n")
#(id: 357, markdown: "_foo bar_\n", html: "<p><em>foo bar</em></p>\n")
#(id: 358, markdown: "_ foo bar_\n", html: "<p>_ foo bar_</p>\n")
#(id: 359, markdown: 'a_"foo"_\n', html: "<p>a_&quot;foo&quot;_</p>\n")
#(id: 360, markdown: "foo_bar_\n", html: "<p>foo_bar_</p>\n")
#(id: 361, markdown: "5_6_78\n", html: "<p>5_6_78</p>\n")
#(id: 362, markdown: "\xd0\xbf\xd1\x80\xd0\xb8\xd1\x81\xd1\x82\xd0\xb0\xd0\xbd\xd1\x8f\xd0\xbc_\xd1\x81\xd1\x82\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8f\xd1\x82\xd1\x81\xd1\x8f_\n", html: "<p>\xd0\xbf\xd1\x80\xd0\xb8\xd1\x81\xd1\x82\xd0\xb0\xd0\xbd\xd1\x8f\xd0\xbc_\xd1\x81\xd1\x82\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8f\xd1\x82\xd1\x81\xd1\x8f_</p>\n")
#(id: 363, markdown: 'aa_"bb"_cc\n', html: "<p>aa_&quot;bb&quot;_cc</p>\n")
#(id: 364, markdown: "foo-_(bar)_\n", html: "<p>foo-<em>(bar)</em></p>\n")
#(id: 365, markdown: "_foo*\n", html: "<p>_foo*</p>\n")
#(id: 366, markdown: "*foo bar *\n", html: "<p>*foo bar *</p>\n")
#(id: 367, markdown: "*foo bar\n*\n", html: "<p>*foo bar\n*</p>\n")
#(id: 368, markdown: "*(*foo)\n", html: "<p>*(*foo)</p>\n")
#(id: 369, markdown: "*(*foo*)*\n", html: "<p><em>(<em>foo</em>)</em></p>\n")
#(id: 370, markdown: "*foo*bar\n", html: "<p><em>foo</em>bar</p>\n")
#(id: 371, markdown: "_foo bar _\n", html: "<p>_foo bar _</p>\n")
#(id: 372, markdown: "_(_foo)\n", html: "<p>_(_foo)</p>\n")
#(id: 373, markdown: "_(_foo_)_\n", html: "<p><em>(<em>foo</em>)</em></p>\n")
#(id: 374, markdown: "_foo_bar\n", html: "<p>_foo_bar</p>\n")
#(id: 375, markdown: "_\xd0\xbf\xd1\x80\xd0\xb8\xd1\x81\xd1\x82\xd0\xb0\xd0\xbd\xd1\x8f\xd0\xbc_\xd1\x81\xd1\x82\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8f\xd1\x82\xd1\x81\xd1\x8f\n", html: "<p>_\xd0\xbf\xd1\x80\xd0\xb8\xd1\x81\xd1\x82\xd0\xb0\xd0\xbd\xd1\x8f\xd0\xbc_\xd1\x81\xd1\x82\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8f\xd1\x82\xd1\x81\xd1\x8f</p>\n")
#(id: 376, markdown: "_foo_bar_baz_\n", html: "<p><em>foo_bar_baz</em></p>\n")
#(id: 377, markdown: "_(bar)_.\n", html: "<p><em>(bar)</em>.</p>\n")
#(id: 378, markdown: "**foo bar**\n", html: "<p><strong>foo bar</strong></p>\n")
#(id: 379, markdown: "** foo bar**\n", html: "<p>** foo bar**</p>\n")
#(id: 380, markdown: 'a**"foo"**\n', html: "<p>a**&quot;foo&quot;**</p>\n")
#(id: 381, markdown: "foo**bar**\n", html: "<p>foo<strong>bar</strong></p>\n")
#(id: 382, markdown: "__foo bar__\n", html: "<p><strong>foo bar</strong></p>\n")
#(id: 383, markdown: "__ foo bar__\n", html: "<p>__ foo bar__</p>\n")
#(id: 384, markdown: "__\nfoo bar__\n", html: "<p>__\nfoo bar__</p>\n")
#(id: 385, markdown: 'a__"foo"__\n', html: "<p>a__&quot;foo&quot;__</p>\n")
#(id: 386, markdown: "foo__bar__\n", html: "<p>foo__bar__</p>\n")
#(id: 387, markdown: "5__6__78\n", html: "<p>5__6__78</p>\n")
#(id: 388, markdown: "\xd0\xbf\xd1\x80\xd0\xb8\xd1\x81\xd1\x82\xd0\xb0\xd0\xbd\xd1\x8f\xd0\xbc__\xd1\x81\xd1\x82\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8f\xd1\x82\xd1\x81\xd1\x8f__\n", html: "<p>\xd0\xbf\xd1\x80\xd0\xb8\xd1\x81\xd1\x82\xd0\xb0\xd0\xbd\xd1\x8f\xd0\xbc__\xd1\x81\xd1\x82\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8f\xd1\x82\xd1\x81\xd1\x8f__</p>\n")
#(id: 389, markdown: "__foo, __bar__, baz__\n", html: "<p><strong>foo, <strong>bar</strong>, baz</strong></p>\n")
#(id: 390, markdown: "foo-__(bar)__\n", html: "<p>foo-<strong>(bar)</strong></p>\n")
#(id: 391, markdown: "**foo bar **\n", html: "<p>**foo bar **</p>\n")
#(id: 392, markdown: "**(**foo)\n", html: "<p>**(**foo)</p>\n")
#(id: 393, markdown: "*(**foo**)*\n", html: "<p><em>(<strong>foo</strong>)</em></p>\n")
#(id: 394, markdown: "**Gomphocarpus (*Gomphocarpus physocarpus*, syn.\n*Asclepias physocarpa*)**\n", html: "<p><strong>Gomphocarpus (<em>Gomphocarpus physocarpus</em>, syn.\n<em>Asclepias physocarpa</em>)</strong></p>\n")
#(id: 395, markdown: '**foo "*bar*" foo**\n', html: "<p><strong>foo &quot;<em>bar</em>&quot; foo</strong></p>\n")
#(id: 396, markdown: "**foo**bar\n", html: "<p><strong>foo</strong>bar</p>\n")
#(id: 397, markdown: "__foo bar __\n", html: "<p>__foo bar __</p>\n")
#(id: 398, markdown: "__(__foo)\n", html: "<p>__(__foo)</p>\n")
#(id: 399, markdown: "_(__foo__)_\n", html: "<p><em>(<strong>foo</strong>)</em></p>\n")
#(id: 400, markdown: "__foo__bar\n", html: "<p>__foo__bar</p>\n")
#(id: 401, markdown: "__\xd0\xbf\xd1\x80\xd0\xb8\xd1\x81\xd1\x82\xd0\xb0\xd0\xbd\xd1\x8f\xd0\xbc__\xd1\x81\xd1\x82\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8f\xd1\x82\xd1\x81\xd1\x8f\n", html: "<p>__\xd0\xbf\xd1\x80\xd0\xb8\xd1\x81\xd1\x82\xd0\xb0\xd0\xbd\xd1\x8f\xd0\xbc__\xd1\x81\xd1\x82\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8f\xd1\x82\xd1\x81\xd1\x8f</p>\n")
#(id: 402, markdown: "__foo__bar__baz__\n", html: "<p><strong>foo__bar__baz</strong></p>\n")
#(id: 403, markdown: "__(bar)__.\n", html: "<p><strong>(bar)</strong>.</p>\n")
#(id: 404, markdown: "*foo [bar](/url)*\n", html: '<p><em>foo <a href="/url">bar</a></em></p>\n')
#(id: 405, markdown: "*foo\nbar*\n", html: "<p><em>foo\nbar</em></p>\n")
#(id: 406, markdown: "_foo __bar__ baz_\n", html: "<p><em>foo <strong>bar</strong> baz</em></p>\n")
#(id: 407, markdown: "_foo _bar_ baz_\n", html: "<p><em>foo <em>bar</em> baz</em></p>\n")
#(id: 408, markdown: "__foo_ bar_\n", html: "<p><em><em>foo</em> bar</em></p>\n")
#(id: 409, markdown: "*foo *bar**\n", html: "<p><em>foo <em>bar</em></em></p>\n")
#(id: 410, markdown: "*foo **bar** baz*\n", html: "<p><em>foo <strong>bar</strong> baz</em></p>\n")
#(id: 411, markdown: "*foo**bar**baz*\n", html: "<p><em>foo<strong>bar</strong>baz</em></p>\n")
#(id: 412, markdown: "*foo**bar*\n", html: "<p><em>foo**bar</em></p>\n")
#(id: 413, markdown: "***foo** bar*\n", html: "<p><em><strong>foo</strong> bar</em></p>\n")
#(id: 414, markdown: "*foo **bar***\n", html: "<p><em>foo <strong>bar</strong></em></p>\n")
#(id: 415, markdown: "*foo**bar***\n", html: "<p><em>foo<strong>bar</strong></em></p>\n")
#(id: 416, markdown: "foo***bar***baz\n", html: "<p>foo<em><strong>bar</strong></em>baz</p>\n")
#(id: 417, markdown: "foo******bar*********baz\n", html: "<p>foo<strong><strong><strong>bar</strong></strong></strong>***baz</p>\n")
#(id: 418, markdown: "*foo **bar *baz* bim** bop*\n", html: "<p><em>foo <strong>bar <em>baz</em> bim</strong> bop</em></p>\n")
#(id: 419, markdown: "*foo [*bar*](/url)*\n", html: '<p><em>foo <a href="/url"><em>bar</em></a></em></p>\n')
#(id: 420, markdown: "** is not an empty emphasis\n", html: "<p>** is not an empty emphasis</p>\n")
#(id: 421, markdown: "**** is not an empty strong emphasis\n", html: "<p>**** is not an empty strong emphasis</p>\n")
#(id: 422, markdown: "**foo [bar](/url)**\n", html: '<p><strong>foo <a href="/url">bar</a></strong></p>\n')
#(id: 423, markdown: "**foo\nbar**\n", html: "<p><strong>foo\nbar</strong></p>\n")
#(id: 424, markdown: "__foo _bar_ baz__\n", html: "<p><strong>foo <em>bar</em> baz</strong></p>\n")
#(id: 425, markdown: "__foo __bar__ baz__\n", html: "<p><strong>foo <strong>bar</strong> baz</strong></p>\n")
#(id: 426, markdown: "____foo__ bar__\n", html: "<p><strong><strong>foo</strong> bar</strong></p>\n")
#(id: 427, markdown: "**foo **bar****\n", html: "<p><strong>foo <strong>bar</strong></strong></p>\n")
#(id: 428, markdown: "**foo *bar* baz**\n", html: "<p><strong>foo <em>bar</em> baz</strong></p>\n")
#(id: 429, markdown: "**foo*bar*baz**\n", html: "<p><strong>foo<em>bar</em>baz</strong></p>\n")
#(id: 430, markdown: "***foo* bar**\n", html: "<p><strong><em>foo</em> bar</strong></p>\n")
#(id: 431, markdown: "**foo *bar***\n", html: "<p><strong>foo <em>bar</em></strong></p>\n")
#(id: 432, markdown: "**foo *bar **baz**\nbim* bop**\n", html: "<p><strong>foo <em>bar <strong>baz</strong>\nbim</em> bop</strong></p>\n")
#(id: 433, markdown: "**foo [*bar*](/url)**\n", html: '<p><strong>foo <a href="/url"><em>bar</em></a></strong></p>\n')
#(id: 434, markdown: "__ is not an empty emphasis\n", html: "<p>__ is not an empty emphasis</p>\n")
#(id: 435, markdown: "____ is not an empty strong emphasis\n", html: "<p>____ is not an empty strong emphasis</p>\n")
#(id: 436, markdown: "foo ***\n", html: "<p>foo ***</p>\n")
#(id: 437, markdown: "foo *\\**\n", html: "<p>foo <em>*</em></p>\n")
#(id: 438, markdown: "foo *_*\n", html: "<p>foo <em>_</em></p>\n")
#(id: 439, markdown: "foo *****\n", html: "<p>foo *****</p>\n")
#(id: 440, markdown: "foo **\\***\n", html: "<p>foo <strong>*</strong></p>\n")
#(id: 441, markdown: "foo **_**\n", html: "<p>foo <strong>_</strong></p>\n")
#(id: 442, markdown: "**foo*\n", html: "<p>*<em>foo</em></p>\n")
#(id: 443, markdown: "*foo**\n", html: "<p><em>foo</em>*</p>\n")
#(id: 444, markdown: "***foo**\n", html: "<p>*<strong>foo</strong></p>\n")
#(id: 445, markdown: "****foo*\n", html: "<p>***<em>foo</em></p>\n")
#(id: 446, markdown: "**foo***\n", html: "<p><strong>foo</strong>*</p>\n")
#(id: 447, markdown: "*foo****\n", html: "<p><em>foo</em>***</p>\n")
#(id: 448, markdown: "foo ___\n", html: "<p>foo ___</p>\n")
#(id: 449, markdown: "foo _\\__\n", html: "<p>foo <em>_</em></p>\n")
#(id: 450, markdown: "foo _*_\n", html: "<p>foo <em>*</em></p>\n")
#(id: 451, markdown: "foo _____\n", html: "<p>foo _____</p>\n")
#(id: 452, markdown: "foo __\\___\n", html: "<p>foo <strong>_</strong></p>\n")
#(id: 453, markdown: "foo __*__\n", html: "<p>foo <strong>*</strong></p>\n")
#(id: 454, markdown: "__foo_\n", html: "<p>_<em>foo</em></p>\n")
#(id: 455, markdown: "_foo__\n", html: "<p><em>foo</em>_</p>\n")
#(id: 456, markdown: "___foo__\n", html: "<p>_<strong>foo</strong></p>\n")
#(id: 457, markdown: "____foo_\n", html: "<p>___<em>foo</em></p>\n")
#(id: 458, markdown: "__foo___\n", html: "<p><strong>foo</strong>_</p>\n")
#(id: 459, markdown: "_foo____\n", html: "<p><em>foo</em>___</p>\n")
#(id: 460, markdown: "**foo**\n", html: "<p><strong>foo</strong></p>\n")
#(id: 461, markdown: "*_foo_*\n", html: "<p><em><em>foo</em></em></p>\n")
#(id: 462, markdown: "__foo__\n", html: "<p><strong>foo</strong></p>\n")
#(id: 463, markdown: "_*foo*_\n", html: "<p><em><em>foo</em></em></p>\n")
#(id: 464, markdown: "****foo****\n", html: "<p><strong><strong>foo</strong></strong></p>\n")
#(id: 465, markdown: "____foo____\n", html: "<p><strong><strong>foo</strong></strong></p>\n")
#(id: 466, markdown: "******foo******\n", html: "<p><strong><strong><strong>foo</strong></strong></strong></p>\n")
#(id: 467, markdown: "***foo***\n", html: "<p><em><strong>foo</strong></em></p>\n")
#(id: 468, markdown: "_____foo_____\n", html: "<p><em><strong><strong>foo</strong></strong></em></p>\n")
#(id: 469, markdown: "*foo _bar* baz_\n", html: "<p><em>foo _bar</em> baz_</p>\n")
#(id: 470, markdown: "*foo __bar *baz bim__ bam*\n", html: "<p><em>foo <strong>bar *baz bim</strong> bam</em></p>\n")
#(id: 471, markdown: "**foo **bar baz**\n", html: "<p>**foo <strong>bar baz</strong></p>\n")
#(id: 472, markdown: "*foo *bar baz*\n", html: "<p>*foo <em>bar baz</em></p>\n")
#(id: 473, markdown: "*[bar*](/url)\n", html: '<p>*<a href="/url">bar*</a></p>\n')
#(id: 474, markdown: "_foo [bar_](/url)\n", html: '<p>_foo <a href="/url">bar_</a></p>\n')
#(id: 475, markdown: '*<img src="foo" title="*"/>\n', html: '<p>*<img src="foo" title="*"/></p>\n')
#(id: 476, markdown: '**<a href="**">\n', html: '<p>**<a href="**"></p>\n')
#(id: 477, markdown: '__<a href="__">\n', html: '<p>__<a href="__"></p>\n')
#(id: 478, markdown: "*a `*`*\n", html: "<p><em>a <code>*</code></em></p>\n")
#(id: 479, markdown: "_a `_`_\n", html: "<p><em>a <code>_</code></em></p>\n")
#(id: 480, markdown: "**a<https://foo.bar/?q=**>\n", html: '<p>**a<a href="https://foo.bar/?q=**">https://foo.bar/?q=**</a></p>\n')
#(id: 481, markdown: "__a<https://foo.bar/?q=__>\n", html: '<p>__a<a href="https://foo.bar/?q=__">https://foo.bar/?q=__</a></p>\n')
#(id: 482, markdown: '[link](/uri "title")\n', html: '<p><a href="/uri" title="title">link</a></p>\n')
#(id: 483, markdown: "[link](/uri)\n", html: '<p><a href="/uri">link</a></p>\n')
#(id: 484, markdown: "[](./target.md)\n", html: '<p><a href="./target.md"></a></p>\n')
#(id: 485, markdown: "[link]()\n", html: '<p><a href="">link</a></p>\n')
#(id: 486, markdown: "[link](<>)\n", html: '<p><a href="">link</a></p>\n')
#(id: 487, markdown: "[]()\n", html: '<p><a href=""></a></p>\n')
#(id: 488, markdown: "[link](/my uri)\n", html: "<p>[link](/my uri)</p>\n")
#(id: 489, markdown: "[link](</my uri>)\n", html: '<p><a href="/my%20uri">link</a></p>\n')
#(id: 490, markdown: "[link](foo\nbar)\n", html: "<p>[link](foo\nbar)</p>\n")
#(id: 491, markdown: "[link](<foo\nbar>)\n", html: "<p>[link](<foo\nbar>)</p>\n")
#(id: 492, markdown: "[a](<b)c>)\n", html: '<p><a href="b)c">a</a></p>\n')
#(id: 493, markdown: "[link](<foo\\>)\n", html: "<p>[link](&lt;foo&gt;)</p>\n")
#(id: 494, markdown: "[a](<b)c\n[a](<b)c>\n[a](<b>c)\n", html: "<p>[a](&lt;b)c\n[a](&lt;b)c&gt;\n[a](<b>c)</p>\n")
#(id: 495, markdown: "[link](\\(foo\\))\n", html: '<p><a href="(foo)">link</a></p>\n')
#(id: 496, markdown: "[link](foo(and(bar)))\n", html: '<p><a href="foo(and(bar))">link</a></p>\n')
#(id: 497, markdown: "[link](foo(and(bar))\n", html: "<p>[link](foo(and(bar))</p>\n")
#(id: 498, markdown: "[link](foo\\(and\\(bar\\))\n", html: '<p><a href="foo(and(bar)">link</a></p>\n')
#(id: 499, markdown: "[link](<foo(and(bar)>)\n", html: '<p><a href="foo(and(bar)">link</a></p>\n')
#(id: 500, markdown: "[link](foo\\)\\:)\n", html: '<p><a href="foo):">link</a></p>\n')
#(id: 501, markdown: "[link](#fragment)\n\n[link](https://example.com#fragment)\n\n[link](https://example.com?foo=3#frag)\n", html: '<p><a href="#fragment">link</a></p>\n<p><a href="https://example.com#fragment">link</a></p>\n<p><a href="https://example.com?foo=3#frag">link</a></p>\n')
#(id: 502, markdown: "[link](foo\\bar)\n", html: '<p><a href="foo%5Cbar">link</a></p>\n')
#(id: 503, markdown: "[link](foo%20b&auml;)\n", html: '<p><a href="foo%20b%C3%A4">link</a></p>\n')
#(id: 504, markdown: '[link]("title")\n', html: '<p><a href="%22title%22">link</a></p>\n')
#(id: 505, markdown: "[link](/url \"title\")\n[link](/url 'title')\n[link](/url (title))\n", html: '<p><a href="/url" title="title">link</a>\n<a href="/url" title="title">link</a>\n<a href="/url" title="title">link</a></p>\n')
#(id: 506, markdown: '[link](/url "title \\"&quot;")\n', html: '<p><a href="/url" title="title &quot;&quot;">link</a></p>\n')
#(id: 507, markdown: '[link](/url\xc2\xa0"title")\n', html: '<p><a href="/url%C2%A0%22title%22">link</a></p>\n')
#(id: 508, markdown: '[link](/url "title "and" title")\n', html: "<p>[link](/url &quot;title &quot;and&quot; title&quot;)</p>\n")
#(id: 509, markdown: "[link](/url 'title \"and\" title')\n", html: '<p><a href="/url" title="title &quot;and&quot; title">link</a></p>\n')
#(id: 510, markdown: '[link](   /uri\n  "title"  )\n', html: '<p><a href="/uri" title="title">link</a></p>\n')
#(id: 511, markdown: "[link] (/uri)\n", html: "<p>[link] (/uri)</p>\n")
#(id: 512, markdown: "[link [foo [bar]]](/uri)\n", html: '<p><a href="/uri">link [foo [bar]]</a></p>\n')
#(id: 513, markdown: "[link] bar](/uri)\n", html: "<p>[link] bar](/uri)</p>\n")
#(id: 514, markdown: "[link [bar](/uri)\n", html: '<p>[link <a href="/uri">bar</a></p>\n')
#(id: 515, markdown: "[link \\[bar](/uri)\n", html: '<p><a href="/uri">link [bar</a></p>\n')
#(id: 516, markdown: "[link *foo **bar** `#`*](/uri)\n", html: '<p><a href="/uri">link <em>foo <strong>bar</strong> <code>#</code></em></a></p>\n')
#(id: 517, markdown: "[![moon](moon.jpg)](/uri)\n", html: '<p><a href="/uri"><img src="moon.jpg" alt="moon" /></a></p>\n')
#(id: 518, markdown: "[foo [bar](/uri)](/uri)\n", html: '<p>[foo <a href="/uri">bar</a>](/uri)</p>\n')
#(id: 519, markdown: "[foo *[bar [baz](/uri)](/uri)*](/uri)\n", html: '<p>[foo <em>[bar <a href="/uri">baz</a>](/uri)</em>](/uri)</p>\n')
#(id: 520, markdown: "![[[foo](uri1)](uri2)](uri3)\n", html: '<p><img src="uri3" alt="[foo](uri2)" /></p>\n')
#(id: 521, markdown: "*[foo*](/uri)\n", html: '<p>*<a href="/uri">foo*</a></p>\n')
#(id: 522, markdown: "[foo *bar](baz*)\n", html: '<p><a href="baz*">foo *bar</a></p>\n')
#(id: 523, markdown: "*foo [bar* baz]\n", html: "<p><em>foo [bar</em> baz]</p>\n")
#(id: 524, markdown: '[foo <bar attr="](baz)">\n', html: '<p>[foo <bar attr="](baz)"></p>\n')
#(id: 525, markdown: "[foo`](/uri)`\n", html: "<p>[foo<code>](/uri)</code></p>\n")
#(id: 526, markdown: "[foo<https://example.com/?search=](uri)>\n", html: '<p>[foo<a href="https://example.com/?search=%5D(uri)">https://example.com/?search=](uri)</a></p>\n')
#(id: 527, markdown: '[foo][bar]\n\n[bar]: /url "title"\n', html: '<p><a href="/url" title="title">foo</a></p>\n')
#(id: 528, markdown: "[link [foo [bar]]][ref]\n\n[ref]: /uri\n", html: '<p><a href="/uri">link [foo [bar]]</a></p>\n')
#(id: 529, markdown: "[link \\[bar][ref]\n\n[ref]: /uri\n", html: '<p><a href="/uri">link [bar</a></p>\n')
#(id: 530, markdown: "[link *foo **bar** `#`*][ref]\n\n[ref]: /uri\n", html: '<p><a href="/uri">link <em>foo <strong>bar</strong> <code>#</code></em></a></p>\n')
#(id: 531, markdown: "[![moon](moon.jpg)][ref]\n\n[ref]: /uri\n", html: '<p><a href="/uri"><img src="moon.jpg" alt="moon" /></a></p>\n')
#(id: 532, markdown: "[foo [bar](/uri)][ref]\n\n[ref]: /uri\n", html: '<p>[foo <a href="/uri">bar</a>]<a href="/uri">ref</a></p>\n')
#(id: 533, markdown: "[foo *bar [baz][ref]*][ref]\n\n[ref]: /uri\n", html: '<p>[foo <em>bar <a href="/uri">baz</a></em>]<a href="/uri">ref</a></p>\n')
#(id: 534, markdown: "*[foo*][ref]\n\n[ref]: /uri\n", html: '<p>*<a href="/uri">foo*</a></p>\n')
#(id: 535, markdown: "[foo *bar][ref]*\n\n[ref]: /uri\n", html: '<p><a href="/uri">foo *bar</a>*</p>\n')
#(id: 536, markdown: '[foo <bar attr="][ref]">\n\n[ref]: /uri\n', html: '<p>[foo <bar attr="][ref]"></p>\n')
#(id: 537, markdown: "[foo`][ref]`\n\n[ref]: /uri\n", html: "<p>[foo<code>][ref]</code></p>\n")
#(id: 538, markdown: "[foo<https://example.com/?search=][ref]>\n\n[ref]: /uri\n", html: '<p>[foo<a href="https://example.com/?search=%5D%5Bref%5D">https://example.com/?search=][ref]</a></p>\n')
#(id: 539, markdown: '[foo][BaR]\n\n[bar]: /url "title"\n', html: '<p><a href="/url" title="title">foo</a></p>\n')
#(id: 540, markdown: "[\xe1\xba\x9e]\n\n[SS]: /url\n", html: '<p><a href="/url">\xe1\xba\x9e</a></p>\n')
#(id: 541, markdown: "[Foo\n  bar]: /url\n\n[Baz][Foo bar]\n", html: '<p><a href="/url">Baz</a></p>\n')
#(id: 542, markdown: '[foo] [bar]\n\n[bar]: /url "title"\n', html: '<p>[foo] <a href="/url" title="title">bar</a></p>\n')
#(id: 543, markdown: '[foo]\n[bar]\n\n[bar]: /url "title"\n', html: '<p>[foo]\n<a href="/url" title="title">bar</a></p>\n')
#(id: 544, markdown: "[foo]: /url1\n\n[foo]: /url2\n\n[bar][foo]\n", html: '<p><a href="/url1">bar</a></p>\n')
#(id: 545, markdown: "[bar][foo\\!]\n\n[foo!]: /url\n", html: "<p>[bar][foo!]</p>\n")
#(id: 546, markdown: "[foo][ref[]\n\n[ref[]: /uri\n", html: "<p>[foo][ref[]</p>\n<p>[ref[]: /uri</p>\n")
#(id: 547, markdown: "[foo][ref[bar]]\n\n[ref[bar]]: /uri\n", html: "<p>[foo][ref[bar]]</p>\n<p>[ref[bar]]: /uri</p>\n")
#(id: 548, markdown: "[[[foo]]]\n\n[[[foo]]]: /url\n", html: "<p>[[[foo]]]</p>\n<p>[[[foo]]]: /url</p>\n")
#(id: 549, markdown: "[foo][ref\\[]\n\n[ref\\[]: /uri\n", html: '<p><a href="/uri">foo</a></p>\n')
#(id: 550, markdown: "[bar\\\\]: /uri\n\n[bar\\\\]\n", html: '<p><a href="/uri">bar\\</a></p>\n')
#(id: 551, markdown: "[]\n\n[]: /uri\n", html: "<p>[]</p>\n<p>[]: /uri</p>\n")
#(id: 552, markdown: "[\n ]\n\n[\n ]: /uri\n", html: "<p>[\n]</p>\n<p>[\n]: /uri</p>\n")
#(id: 553, markdown: '[foo][]\n\n[foo]: /url "title"\n', html: '<p><a href="/url" title="title">foo</a></p>\n')
#(id: 554, markdown: '[*foo* bar][]\n\n[*foo* bar]: /url "title"\n', html: '<p><a href="/url" title="title"><em>foo</em> bar</a></p>\n')
#(id: 555, markdown: '[Foo][]\n\n[foo]: /url "title"\n', html: '<p><a href="/url" title="title">Foo</a></p>\n')
#(id: 556, markdown: '[foo] \n[]\n\n[foo]: /url "title"\n', html: '<p><a href="/url" title="title">foo</a>\n[]</p>\n')
#(id: 557, markdown: '[foo]\n\n[foo]: /url "title"\n', html: '<p><a href="/url" title="title">foo</a></p>\n')
#(id: 558, markdown: '[*foo* bar]\n\n[*foo* bar]: /url "title"\n', html: '<p><a href="/url" title="title"><em>foo</em> bar</a></p>\n')
#(id: 559, markdown: '[[*foo* bar]]\n\n[*foo* bar]: /url "title"\n', html: '<p>[<a href="/url" title="title"><em>foo</em> bar</a>]</p>\n')
#(id: 560, markdown: "[[bar [foo]\n\n[foo]: /url\n", html: '<p>[[bar <a href="/url">foo</a></p>\n')
#(id: 561, markdown: '[Foo]\n\n[foo]: /url "title"\n', html: '<p><a href="/url" title="title">Foo</a></p>\n')
#(id: 562, markdown: "[foo] bar\n\n[foo]: /url\n", html: '<p><a href="/url">foo</a> bar</p>\n')
#(id: 563, markdown: '\\[foo]\n\n[foo]: /url "title"\n', html: "<p>[foo]</p>\n")
#(id: 564, markdown: "[foo*]: /url\n\n*[foo*]\n", html: '<p>*<a href="/url">foo*</a></p>\n')
#(id: 565, markdown: "[foo][bar]\n\n[foo]: /url1\n[bar]: /url2\n", html: '<p><a href="/url2">foo</a></p>\n')
#(id: 566, markdown: "[foo][]\n\n[foo]: /url1\n", html: '<p><a href="/url1">foo</a></p>\n')
#(id: 567, markdown: "[foo]()\n\n[foo]: /url1\n", html: '<p><a href="">foo</a></p>\n')
#(id: 568, markdown: "[foo](not a link)\n\n[foo]: /url1\n", html: '<p><a href="/url1">foo</a>(not a link)</p>\n')
#(id: 569, markdown: "[foo][bar][baz]\n\n[baz]: /url\n", html: '<p>[foo]<a href="/url">bar</a></p>\n')
#(id: 570, markdown: "[foo][bar][baz]\n\n[baz]: /url1\n[bar]: /url2\n", html: '<p><a href="/url2">foo</a><a href="/url1">baz</a></p>\n')
#(id: 571, markdown: "[foo][bar][baz]\n\n[baz]: /url1\n[foo]: /url2\n", html: '<p>[foo]<a href="/url1">bar</a></p>\n')
#(id: 572, markdown: '![foo](/url "title")\n', html: '<p><img src="/url" alt="foo" title="title" /></p>\n')
#(id: 573, markdown: '![foo *bar*]\n\n[foo *bar*]: train.jpg "train & tracks"\n', html: '<p><img src="train.jpg" alt="foo bar" title="train &amp; tracks" /></p>\n')
#(id: 574, markdown: "![foo ![bar](/url)](/url2)\n", html: '<p><img src="/url2" alt="foo bar" /></p>\n')
#(id: 575, markdown: "![foo [bar](/url)](/url2)\n", html: '<p><img src="/url2" alt="foo bar" /></p>\n')
#(id: 576, markdown: '![foo *bar*][]\n\n[foo *bar*]: train.jpg "train & tracks"\n', html: '<p><img src="train.jpg" alt="foo bar" title="train &amp; tracks" /></p>\n')
#(id: 577, markdown: '![foo *bar*][foobar]\n\n[FOOBAR]: train.jpg "train & tracks"\n', html: '<p><img src="train.jpg" alt="foo bar" title="train &amp; tracks" /></p>\n')
#(id: 578, markdown: "![foo](train.jpg)\n", html: '<p><img src="train.jpg" alt="foo" /></p>\n')
#(id: 579, markdown: 'My ![foo bar](/path/to/train.jpg  "title"   )\n', html: '<p>My <img src="/path/to/train.jpg" alt="foo bar" title="title" /></p>\n')
#(id: 580, markdown: "![foo](<url>)\n", html: '<p><img src="url" alt="foo" /></p>\n')
#(id: 581, markdown: "![](/url)\n", html: '<p><img src="/url" alt="" /></p>\n')
#(id: 582, markdown: "![foo][bar]\n\n[bar]: /url\n", html: '<p><img src="/url" alt="foo" /></p>\n')
#(id: 583, markdown: "![foo][bar]\n\n[BAR]: /url\n", html: '<p><img src="/url" alt="foo" /></p>\n')
#(id: 584, markdown: '![foo][]\n\n[foo]: /url "title"\n', html: '<p><img src="/url" alt="foo" title="title" /></p>\n')
#(id: 585, markdown: '![*foo* bar][]\n\n[*foo* bar]: /url "title"\n', html: '<p><img src="/url" alt="foo bar" title="title" /></p>\n')
#(id: 586, markdown: '![Foo][]\n\n[foo]: /url "title"\n', html: '<p><img src="/url" alt="Foo" title="title" /></p>\n')
#(id: 587, markdown: '![foo] \n[]\n\n[foo]: /url "title"\n', html: '<p><img src="/url" alt="foo" title="title" />\n[]</p>\n')
#(id: 588, markdown: '![foo]\n\n[foo]: /url "title"\n', html: '<p><img src="/url" alt="foo" title="title" /></p>\n')
#(id: 589, markdown: '![*foo* bar]\n\n[*foo* bar]: /url "title"\n', html: '<p><img src="/url" alt="foo bar" title="title" /></p>\n')
#(id: 590, markdown: '![[foo]]\n\n[[foo]]: /url "title"\n', html: "<p>![[foo]]</p>\n<p>[[foo]]: /url &quot;title&quot;</p>\n")
#(id: 591, markdown: '![Foo]\n\n[foo]: /url "title"\n', html: '<p><img src="/url" alt="Foo" title="title" /></p>\n')
#(id: 592, markdown: '!\\[foo]\n\n[foo]: /url "title"\n', html: "<p>![foo]</p>\n")
#(id: 593, markdown: '\\![foo]\n\n[foo]: /url "title"\n', html: '<p>!<a href="/url" title="title">foo</a></p>\n')
#(id: 594, markdown: "<http://foo.bar.baz>\n", html: '<p><a href="http://foo.bar.baz">http://foo.bar.baz</a></p>\n')
#(id: 595, markdown: "<https://foo.bar.baz/test?q=hello&id=22&boolean>\n", html: '<p><a href="https://foo.bar.baz/test?q=hello&amp;id=22&amp;boolean">https://foo.bar.baz/test?q=hello&amp;id=22&amp;boolean</a></p>\n')
#(id: 596, markdown: "<irc://foo.bar:2233/baz>\n", html: '<p><a href="irc://foo.bar:2233/baz">irc://foo.bar:2233/baz</a></p>\n')
#(id: 597, markdown: "<MAILTO:FOO@BAR.BAZ>\n", html: '<p><a href="MAILTO:FOO@BAR.BAZ">MAILTO:FOO@BAR.BAZ</a></p>\n')
#(id: 598, markdown: "<a+b+c:d>\n", html: '<p><a href="a+b+c:d">a+b+c:d</a></p>\n')
#(id: 599, markdown: "<made-up-scheme://foo,bar>\n", html: '<p><a href="made-up-scheme://foo,bar">made-up-scheme://foo,bar</a></p>\n')
#(id: 600, markdown: "<https://../>\n", html: '<p><a href="https://../">https://../</a></p>\n')
#(id: 601, markdown: "<localhost:5001/foo>\n", html: '<p><a href="localhost:5001/foo">localhost:5001/foo</a></p>\n')
#(id: 602, markdown: "<https://foo.bar/baz bim>\n", html: "<p>&lt;https://foo.bar/baz bim&gt;</p>\n")
#(id: 603, markdown: "<https://example.com/\\[\\>\n", html: '<p><a href="https://example.com/%5C%5B%5C">https://example.com/\\[\\</a></p>\n')
#(id: 604, markdown: "<foo@bar.example.com>\n", html: '<p><a href="mailto:foo@bar.example.com">foo@bar.example.com</a></p>\n')
#(id: 605, markdown: "<foo+special@Bar.baz-bar0.com>\n", html: '<p><a href="mailto:foo+special@Bar.baz-bar0.com">foo+special@Bar.baz-bar0.com</a></p>\n')
#(id: 606, markdown: "<foo\\+@bar.example.com>\n", html: "<p>&lt;foo+@bar.example.com&gt;</p>\n")
#(id: 607, markdown: "<>\n", html: "<p>&lt;&gt;</p>\n")
#(id: 608, markdown: "< https://foo.bar >\n", html: "<p>&lt; https://foo.bar &gt;</p>\n")
#(id: 609, markdown: "<m:abc>\n", html: "<p>&lt;m:abc&gt;</p>\n")
#(id: 610, markdown: "<foo.bar.baz>\n", html: "<p>&lt;foo.bar.baz&gt;</p>\n")
#(id: 611, markdown: "https://example.com\n", html: "<p>https://example.com</p>\n")
#(id: 612, markdown: "foo@bar.example.com\n", html: "<p>foo@bar.example.com</p>\n")
#(id: 613, markdown: "<a><bab><c2c>\n", html: "<p><a><bab><c2c></p>\n")
#(id: 614, markdown: "<a/><b2/>\n", html: "<p><a/><b2/></p>\n")
#(id: 615, markdown: '<a  /><b2\ndata="foo" >\n', html: '<p><a  /><b2\ndata="foo" ></p>\n')
#(id: 616, markdown: '<a foo="bar" bam = \'baz <em>"</em>\'\n_boolean zoop:33=zoop:33 />\n', html: '<p><a foo="bar" bam = \'baz <em>"</em>\'\n_boolean zoop:33=zoop:33 /></p>\n')
#(id: 617, markdown: 'Foo <responsive-image src="foo.jpg" />\n', html: '<p>Foo <responsive-image src="foo.jpg" /></p>\n')
#(id: 618, markdown: "<33> <__>\n", html: "<p>&lt;33&gt; &lt;__&gt;</p>\n")
#(id: 619, markdown: '<a h*#ref="hi">\n', html: "<p>&lt;a h*#ref=&quot;hi&quot;&gt;</p>\n")
#(id: 620, markdown: "<a href=\"hi'> <a href=hi'>\n", html: "<p>&lt;a href=&quot;hi'&gt; &lt;a href=hi'&gt;</p>\n")
#(id: 621, markdown: "< a><\nfoo><bar/ >\n<foo bar=baz\nbim!bop />\n", html: "<p>&lt; a&gt;&lt;\nfoo&gt;&lt;bar/ &gt;\n&lt;foo bar=baz\nbim!bop /&gt;</p>\n")
#(id: 622, markdown: "<a href='bar'title=title>\n", html: "<p>&lt;a href='bar'title=title&gt;</p>\n")
#(id: 623, markdown: "</a></foo >\n", html: "<p></a></foo ></p>\n")
#(id: 624, markdown: '</a href="foo">\n', html: "<p>&lt;/a href=&quot;foo&quot;&gt;</p>\n")
#(id: 625, markdown: "foo <!-- this is a --\ncomment - with hyphens -->\n", html: "<p>foo <!-- this is a --\ncomment - with hyphens --></p>\n")
#(id: 626, markdown: "foo <!--> foo -->\n\nfoo <!---> foo -->\n", html: "<p>foo <!--> foo --&gt;</p>\n<p>foo <!---> foo --&gt;</p>\n")
#(id: 627, markdown: "foo <?php echo $a; ?>\n", html: "<p>foo <?php echo $a; ?></p>\n")
#(id: 628, markdown: "foo <!ELEMENT br EMPTY>\n", html: "<p>foo <!ELEMENT br EMPTY></p>\n")
#(id: 629, markdown: "foo <![CDATA[>&<]]>\n", html: "<p>foo <![CDATA[>&<]]></p>\n")
#(id: 630, markdown: 'foo <a href="&ouml;">\n', html: '<p>foo <a href="&ouml;"></p>\n')
#(id: 631, markdown: 'foo <a href="\\*">\n', html: '<p>foo <a href="\\*"></p>\n')
#(id: 632, markdown: '<a href="\\"">\n', html: "<p>&lt;a href=&quot;&quot;&quot;&gt;</p>\n")
#(id: 633, markdown: "foo  \nbaz\n", html: "<p>foo<br />\nbaz</p>\n")
#(id: 634, markdown: "foo\\\nbaz\n", html: "<p>foo<br />\nbaz</p>\n")
#(id: 635, markdown: "foo       \nbaz\n", html: "<p>foo<br />\nbaz</p>\n")
#(id: 636, markdown: "foo  \n     bar\n", html: "<p>foo<br />\nbar</p>\n")
#(id: 637, markdown: "foo\\\n     bar\n", html: "<p>foo<br />\nbar</p>\n")
#(id: 638, markdown: "*foo  \nbar*\n", html: "<p><em>foo<br />\nbar</em></p>\n")
#(id: 639, markdown: "*foo\\\nbar*\n", html: "<p><em>foo<br />\nbar</em></p>\n")
#(id: 640, markdown: "`code  \nspan`\n", html: "<p><code>code   span</code></p>\n")
#(id: 641, markdown: "`code\\\nspan`\n", html: "<p><code>code\\ span</code></p>\n")
#(id: 642, markdown: '<a href="foo  \nbar">\n', html: '<p><a href="foo  \nbar"></p>\n')
#(id: 643, markdown: '<a href="foo\\\nbar">\n', html: '<p><a href="foo\\\nbar"></p>\n')
#(id: 644, markdown: "foo\\\n", html: "<p>foo\\</p>\n")
#(id: 645, markdown: "foo  \n", html: "<p>foo</p>\n")
#(id: 646, markdown: "### foo\\\n", html: "<h3>foo\\</h3>\n")
#(id: 647, markdown: "### foo  \n", html: "<h3>foo</h3>\n")
#(id: 648, markdown: "foo\nbaz\n", html: "<p>foo\nbaz</p>\n")
#(id: 649, markdown: "foo \n baz\n", html: "<p>foo\nbaz</p>\n")
#(id: 650, markdown: "hello $.;'there\n", html: "<p>hello $.;'there</p>\n")
#(id: 651, markdown: "Foo \xcf\x87\xcf\x81\xe1\xbf\x86\xce\xbd\n", html: "<p>Foo \xcf\x87\xcf\x81\xe1\xbf\x86\xce\xbd</p>\n")
#(id: 652, markdown: "Multiple     spaces\n", html: "<p>Multiple     spaces</p>\n")
)