// Code generated by "stringer -type=Token"; DO NOT EDIT.

package tokens

import "strconv"

const _Token_name = "NilEofErrorIdentifierNumberStringWhitespaceCommentNewlineHashCommaSemicolonAtLParenRParenLBracketRBracketLCurlyRCurlyRangeToRangeLenNotBitNotNewDotIsIsntMatchMatchNotLtLteGtGteQMarkColonAssocStartAndOrBitOrBitAndBitXorAddSubCatMulDivAssocEndModLShiftRShiftIncPostIncDecPostDecAssignStartEqAddEqSubEqCatEqMulEqDivEqModEqLShiftEqRShiftEqBitOrEqBitAndEqBitXorEqAssignEndInBreakCaseCatchClassContinueDefaultDoElseFalseForForeverFunctionIfReturnSwitchSuperThisThrowTrueTryWhile"

var _Token_index = [...]uint16{0, 3, 6, 11, 21, 27, 33, 43, 50, 57, 61, 66, 75, 77, 83, 89, 97, 105, 111, 117, 124, 132, 135, 141, 144, 147, 149, 153, 158, 166, 168, 171, 173, 176, 181, 186, 196, 199, 201, 206, 212, 218, 221, 224, 227, 230, 233, 241, 244, 250, 256, 259, 266, 269, 276, 287, 289, 294, 299, 304, 309, 314, 319, 327, 335, 342, 350, 358, 367, 369, 374, 378, 383, 388, 396, 403, 405, 409, 414, 417, 424, 432, 434, 440, 446, 451, 455, 460, 464, 467, 472}

func (i Token) String() string {
	if i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
