// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package regex

// PatternCache is a cache with a crude approximation of LRU.
// Working set should fit in size.
// NOT thread safe.
type PatternCache struct {
	old   map[string]Pattern
	cur   map[string]Pattern
	size  int
	fn    func(string) Pattern
	nget  int
	nmiss int
}

func NewPatternCache(size int, fn func(string) Pattern) *PatternCache {
	return &PatternCache{cur: make(map[string]Pattern, size),
		old: make(map[string]Pattern), size: size, fn: fn}
}

func (c *PatternCache) Get(key string) Pattern {
	c.nget++
	val, ok := c.cur[key]
	if ok {
		return val
	}
	val, ok = c.old[key]
	if !ok {
		c.nmiss++
		val = c.fn(key)
	}
	if len(c.cur) >= c.size {
		c.old = c.cur
		c.cur = make(map[string]Pattern, c.size)
	}
	c.cur[key] = val
	return val
}

func (c *PatternCache) NGet() int {
	return c.nget
}

func (c *PatternCache) NMiss() int {
	return c.nmiss
}
