// Copyright (C) 2026 Suneido Software Corp. All rights reserved worldwide.
Test
	{
	Test_golden()
		{
		.same(AstFormatter(.src(.unfmt())), .fmt())
		.same(AstFormatter(.src(.fmt())), .fmt()) // formatter must be a fixpoint
		}

	src(lines)
		{
		return lines.Join('\n') $ '\n'
		}

	// line by line comparison for easier debugging
	same(actual, want)
		{
		lines = actual.Lines()
		n = lines.Size() > want.Size() ? lines.Size() : want.Size()
		for (i = 0; i < n; ++i)
			Assert(lines.GetDefault(i, "<end of record>")
				is: want.GetDefault(i, "<end of record>"), msg: "line " $ (i + 1))
		}

	unfmt()
		{
		return [
			"// AstFormatter golden fixture deliberately badly formatted.",
			"// Every difference between unfmt and fmt below is one formatting rule.",
			"class : Controller",
			'{',
			"  // scalar member runs align; a method breaks the run",
			'  Name: "golden"',
			"  Title: 'Golden Sample'",
			"  Width: 12345",
			"  Mask: 0x12349876",
			"  Enabled: true",
			"",
			"  // >= 3 uniform rows align as a grid",
			"  Rates: (",
			"\t(state: 'mo', rate: 5, cap: 12345),",
			'\t(state: "ks", rate: 70, cap: 6000),',
			"\t(state: #ne, rate: 300, cap: 100000))",
			"",
			"  // written one per line, so it stays one per line, with commas",
			"  Columns: (",
			'\t#(name, "Name"),',
			'\t#(title, "Title")',
			"\t)",
			"",
			"  // not broken by the author, so it reflows to the width",
			"  Colors: #(red, green, blue, cyan, magenta, yellow, black, white, gray, " $
				"brown, pink)",
			"",
			"  // an empty body hugs the signature",
			"  Reset() {}",
			"",
			"  New(rec) {",
			"\t.rec = rec",
			"\tthis.total = 0 // explicit this on a lowercase member is kept",
			"  }",
			"",
			"  // a break the author wrote between arguments is kept, the other gaps fill",
			"  Calc(x, y) {",
			"\ttotal = Sum(first_argument, second_argument,",
			"\t  third_argument, fourth_argument)",
			"\tvertical = Sum(one,",
			"\t  two,",
			"\t  three)",
			"\tfilled = Sum(alpha_argument, beta_argument, gamma_argument, delta_argument, epsilon_arg)",
			"\treturn total + vertical + filled ;",
			"  }",
			"",
			"  // a sole argument breaks after ( only when that is what makes it fit",
			"  Wrap(secs) {",
			"\tSleep(10 /*= startup */ + (secs * 1.75).Int()) " $
				"/*= allow for the timer running over */",
			"\tRegister(.a_long_argument_that_fits_on_its_own_line_but_not_next_to_the_callee_name)",
			"  }",
			"",
			"  // single statement bodies unbrace, if parens strip, tight arithmetic",
			"  Update(x, y, n) {",
			"\tif (x > 0) { .total += x*2 + y }",
			"\twhile (n > 0) { n -= 1 }",
			"\tfor (i = 0; i < n; i++) { .Add(i+1) }",
			"  }",
			"",
			"  // x++ in statement position becomes x += 1, in value position it stays",
			"  Count(ob) {",
			"\tn = 0",
			"\tob.Each() { n++ }",
			"\tn++",
			"\treturn n",
			"  }",
			"",
			"  // 'c' for one character, #word for identifiers, \"...\" otherwise",
			"  Strings() {",
			'\ta = "x"',
			"\tb = 'hello'",
			"\tc = \"don't\"",
			'\td = "[a-z]+\\d"',
			"\te = 'a\\tb'",
			"\tf = 'line one",
			"line two'",
			"\treturn a $ b $ c $ d $ e $ f",
			"  }",
			"",
			"  // catch (unused) drops the variable, a zero range index drops, " $
				"?true:false folds",
			"  Load(s) {",
			"\ttry",
			"\t  x = s[0 .. 5]",
			"\tcatch (unused)",
			"\t  x = s[0 :: 2]",
			"\treturn x is '' ? false : true",
			"  }",
			"",
			"  // a chain of dotted calls breaks all or nothing",
			"  Clean(s) {",
			"\treturn s.Replace('&lt;', '<').Replace('&gt;', '>').Replace('&amp;', '&').Trim().Upper()",
			"  }",
			"",
			"  // switch drops the parens around its subject",
			"  Kind(x) {",
			"\tswitch (x) {",
			"\tcase 1:",
			"\t  return #one",
			"\tcase 2:",
			"\t  return #two",
			"\tdefault:",
			"\t  return #other",
			"\t}",
			"  }",
			"",
			"  // a debug statement at the margin stays there, an indented one does not",
			"  Dump(ob) {",
			"Print(ob)",
			"\tPrint(ob.Size())",
			"\treturn ob",
			"  }",
			"",
			"  // a block argument indents from the statement, not the argument list",
			"  Later(x) {",
			"\tWin.SetTimeout({",
			"\t\t.f(x)",
			"\t\t}, 0)",
			"\treturn .lines.Fold(0, {|sum, line|",
			"\t\tsum + line.amount",
			"\t\t})",
			"  }",
			"",
			"  // a long string splits at a word boundary, ? : lead the continuation",
			"  Message(n) {",
			'\treturn n > 0 ? "this is a fairly long message that will not fit on one single line at all and so it has to be split" : ""',
			"  }",
			"",
			"  // a nested table written one per line keeps its shape",
			"  Layout: (",
			"\t(Vert,",
			'\t  (Static, "one"),',
			'\t  (Static, "two")),',
			"\t(Horz,",
			'\t  (Button, "OK")))',
			"",
			"  // while true and for (;;) both become forever",
			"  Poll() {",
			"\twhile (true) {",
			"\t  if (.Done?()) { break }",
			"\t}",
			"\tfor (;;) {",
			"\t  break",
			"\t}",
			"  }",
			"",
			"  // else { if } rejoins as else if; a comment before } keeps the braces",
			"  Route(x) {",
			"\tif (x is 1) {",
			"\t  .One()",
			"\t} else {",
			"\t  if (x is 2) {",
			"\t\t.Two()",
			"\t  } else {",
			"\t\t.Other()",
			"\t  }",
			"\t}",
			"\tif (x is 3) {",
			"\t  .Three()",
			"\t  // keep the braces",
			"\t}",
			"  }",
			"",
			"  // an unnamed then keyword-like argument keeps the authored no-comma form",
			"  Check(x) {",
			"\tAssert(x is: 1)",
			"\treturn new Controller()",
			"  }",
			"",
			"",
			"",
			"  // three blank lines above collapse to one",
			"  Spacer() {",
			"\treturn 1",
			"  }",
			"",
			"  // brackets keep the type: all named is a Record, any unnamed is an Object",
			"  Tables() {",
			"\trec = Record(a: 1, b: 2)",
			"\tob = Object(1, 2, 3)",
			"\treturn [rec, ob]",
			"  }",
			"",
			"  // :name shorthand, and ob['x'] becomes ob.x",
			"  Args(name, value) {",
			"\tob = Object(name: name, value: value)",
			"\treturn F(name: name, x: ob['value'])",
			"  }",
			"",
			"  // and / or end the line; not (a is b) is left exactly as written",
			"  Ready?(a, b, c) {",
			"\treturn a.Something?() and b.SomethingElse?() and c.YetAnotherThing?() and not (a is b)",
			"  }",
			"",
			"  // an annotation hugs its token",
			"  Handler(x, y /*unused*/) {",
			"// this margin comment is commented out code, kept at column 0",
			"//x = 0",
			"\treturn x",
			"  }",
			'}']
		}

	fmt()
		{
		return [
			"// AstFormatter golden fixture deliberately badly formatted.",
			"// Every difference between unfmt and fmt below is one formatting rule.",
			#Controller,
			"\t{",
			"\t// scalar member runs align; a method breaks the run",
			"\tName:  #golden",
			'\tTitle: "Golden Sample"',
			"\tWidth: 12_345",
			"\tMask:  0x1234_9876",
			"\tEnabled: true",
			"",
			"\t// >= 3 uniform rows align as a grid",
			"\tRates: (",
			"\t\t(state: mo, rate: 5,   cap: 12_345),",
			"\t\t(state: ks, rate: 70,  cap: 6000),",
			"\t\t(state: ne, rate: 300, cap: 100_000)",
			"\t\t)",
			"",
			"\t// written one per line, so it stays one per line, with commas",
			"\tColumns: (",
			"\t\t(name, Name),",
			"\t\t(title, Title)",
			"\t\t)",
			"",
			"\t// not broken by the author, so it reflows to the width",
			"\tColors: (red, green, blue, cyan, magenta, yellow, black, white, gray, brown, pink)",
			"",
			"\t// an empty body hugs the signature",
			"\tReset() { }",
			"",
			"\tNew(rec)",
			"\t\t{",
			"\t\t.rec = rec",
			"\t\tthis.total = 0 // explicit this on a lowercase member is kept",
			"\t\t}",
			"",
			"\t// a break the author wrote between arguments is kept, the other gaps fill",
			"\tCalc(x, y)",
			"\t\t{",
			"\t\ttotal = Sum(first_argument, second_argument,",
			"\t\t\tthird_argument, fourth_argument)",
			"\t\tvertical = Sum(one,",
			"\t\t\ttwo,",
			"\t\t\tthree)",
			"\t\tfilled = Sum(alpha_argument, beta_argument, gamma_argument, delta_argument,",
			"\t\t\tepsilon_arg)",
			"\t\treturn total + vertical + filled",
			"\t\t}",
			"",
			"\t// a sole argument breaks after ( only when that is what makes it fit",
			"\tWrap(secs)",
			"\t\t{",
			"\t\tSleep(10 /*= startup */ +",
			"\t\t\t(secs * 1.75).Int()) /*= allow for the timer running over */",
			"\t\tRegister(",
			"\t\t\t.a_long_argument_that_fits_on_its_own_line_but_not_next_to_the_callee_name)",
			"\t\t}",
			"",
			"\t// single statement bodies unbrace, if parens strip, tight arithmetic",
			"\tUpdate(x, y, n)",
			"\t\t{",
			"\t\tif x > 0",
			"\t\t\t.total += x*2 + y",
			"\t\twhile n > 0",
			"\t\t\tn -= 1",
			"\t\tfor (i = 0; i < n; i += 1)",
			"\t\t\t.Add(i + 1)",
			"\t\t}",
			"",
			"\t// x++ in statement position becomes x += 1, in value position it stays",
			"\tCount(ob)",
			"\t\t{",
			"\t\tn = 0",
			"\t\tob.Each()",
			"\t\t\t{",
			"\t\t\tn++",
			"\t\t\t}",
			"\t\tn += 1",
			"\t\treturn n",
			"\t\t}",
			"",
			"\t// 'c' for one character, #word for identifiers, \"...\" otherwise",
			"\tStrings()",
			"\t\t{",
			"\t\ta = 'x'",
			"\t\tb = #hello",
			"\t\tc = \"don't\"",
			'\t\td = "[a-z]+\\d"',
			'\t\te = "a\\tb"',
			'\t\tf = "line one',
			'line two"',
			"\t\treturn a $ b $ c $ d $ e $ f",
			"\t\t}",
			"",
			"\t// catch (unused) drops the variable, a zero range index drops, ?true:false folds",
			"\tLoad(s)",
			"\t\t{",
			"\t\ttry",
			"\t\t\tx = s[..5]",
			"\t\tcatch",
			"\t\t\tx = s[::2]",
			'\t\treturn x isnt ""',
			"\t\t}",
			"",
			"\t// a chain of dotted calls breaks all or nothing",
			"\tClean(s)",
			"\t\t{",
			"\t\treturn s.",
			"\t\t\tReplace(\"&lt;\", '<').",
			"\t\t\tReplace(\"&gt;\", '>').",
			"\t\t\tReplace(\"&amp;\", '&').",
			"\t\t\tTrim().",
			"\t\t\tUpper()",
			"\t\t}",
			"",
			"\t// switch drops the parens around its subject",
			"\tKind(x)",
			"\t\t{",
			"\t\tswitch x",
			"\t\t\t{",
			"\t\tcase 1:",
			"\t\t\treturn #one",
			"\t\tcase 2:",
			"\t\t\treturn #two",
			"\t\tdefault:",
			"\t\t\treturn #other",
			"\t\t\t}",
			"\t\t}",
			"",
			"\t// a debug statement at the margin stays there, an indented one does not",
			"\tDump(ob)",
			"\t\t{",
			"Print(ob)",
			"\t\tPrint(ob.Size())",
			"\t\treturn ob",
			"\t\t}",
			"",
			"\t// a block argument indents from the statement, not the argument list",
			"\tLater(x)",
			"\t\t{",
			"\t\tWin.SetTimeout(",
			"\t\t\t{",
			"\t\t\t.f(x)",
			"\t\t\t}, 0)",
			"\t\treturn .lines.Fold(0,",
			"\t\t\t{|sum, line|",
			"\t\t\tsum + line.amount",
			"\t\t\t})",
			"\t\t}",
			"",
			"\t// a long string splits at a word boundary, ? : lead the continuation",
			"\tMessage(n)",
			"\t\t{",
			"\t\treturn n > 0",
			'\t\t\t? "this is a fairly long message that will not fit on one single line at " $',
			'\t\t\t\t"all and so it has to be split"',
			'\t\t\t: ""',
			"\t\t}",
			"",
			"\t// a nested table written one per line keeps its shape",
			"\tLayout: (",
			"\t\t(Vert,",
			"\t\t\t(Static, one),",
			"\t\t\t(Static, two)),",
			"\t\t(Horz,",
			"\t\t\t(Button, OK))",
			"\t\t)",
			"",
			"\t// while true and for (;;) both become forever",
			"\tPoll()",
			"\t\t{",
			"\t\tforever",
			"\t\t\tif .Done?()",
			"\t\t\t\tbreak",
			"\t\tforever",
			"\t\t\tbreak",
			"\t\t}",
			"",
			"\t// else { if } rejoins as else if; a comment before } keeps the braces",
			"\tRoute(x)",
			"\t\t{",
			"\t\tif x is 1",
			"\t\t\t.One()",
			"\t\telse if x is 2",
			"\t\t\t.Two()",
			"\t\telse",
			"\t\t\t.Other()",
			"\t\tif x is 3",
			"\t\t\t{",
			"\t\t\t.Three()",
			"\t\t\t// keep the braces",
			"\t\t\t}",
			"\t\t}",
			"",
			"\t// an unnamed then keyword-like argument keeps the authored no-comma form",
			"\tCheck(x)",
			"\t\t{",
			"\t\tAssert(x is: 1)",
			"\t\treturn new Controller()",
			"\t\t}",
			"",
			"\t// three blank lines above collapse to one",
			"\tSpacer()",
			"\t\t{",
			"\t\treturn 1",
			"\t\t}",
			"",
			"\t// brackets keep the type: all named is a Record, any unnamed is an Object",
			"\tTables()",
			"\t\t{",
			"\t\trec = [a: 1, b: 2]",
			"\t\tob = [1, 2, 3]",
			"\t\treturn [rec, ob]",
			"\t\t}",
			"",
			"\t// :name shorthand, and ob['x'] becomes ob.x",
			"\tArgs(name, value)",
			"\t\t{",
			"\t\tob = Object(:name, :value)",
			"\t\treturn F(:name, x: ob.value)",
			"\t\t}",
			"",
			"\t// and / or end the line; not (a is b) is left exactly as written",
			"\tReady?(a, b, c)",
			"\t\t{",
			"\t\treturn a.Something?() and b.SomethingElse?() and c.YetAnotherThing?() and",
			"\t\t\tnot (a is b)",
			"\t\t}",
			"",
			"\t// an annotation hugs its token",
			"\tHandler(x, y/*unused*/)",
			"\t\t{",
			"// this margin comment is commented out code, kept at column 0",
			"//x = 0",
			"\t\treturn x",
			"\t\t}",
			"\t}"]
		}
	}
