// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright Suneido Software Corp. All rights reserved.
// Governed by the MIT license found in the LICENSE file.

package meta

import (
	"math/bits"
	"sort"

	"github.com/apmckinlay/gsuneido/database/db19/stor"
	"github.com/apmckinlay/gsuneido/util/verify"
)

type InfoHtbl struct {
	slots []*Info
	// nitems is the current number of key/values in the map
	nitems int
	// cap is the limit for nitems before resizing
	cap int
	// shift is used by hashToIndex
	shift int
	// mask is used to wrap around
	mask int
}

// NewInfoHtbl creates a new InfoHtbl with roughly the specified capacity
func NewInfoHtbl(cap int) *InfoHtbl {
	nextPow2 := func(n int) (int, int) {
		bl := bits.Len(uint(n))
		return 1 << bl, 32 - bl
	}
	const loadPercent = 70
	if cap < 9 {
		cap = 9
	}
	size, shift := nextPow2(cap * 100 / loadPercent)
	return &InfoHtbl{slots: make([]*Info, size),
		shift: shift, mask: size - 1, cap: size * loadPercent / 100}
}

func (h *InfoHtbl) Put(item *Info) {
	if h.nitems >= h.cap {
		h.grow()
	}
	key := h.keyOf(item)
	for i := h.hashToIndex(h.hash(key)); ; i = (i + 1) & h.mask {
		if h.slots[i] == nil {
			h.nitems++
		} else if h.keyOf(h.slots[i]) != key {
			continue
		}
		h.slots[i] = item
		return
	}
}

func (h *InfoHtbl) Get(key string) *Info {
	for i := h.hashToIndex(h.hash(key)); ; i = (i + 1) & h.mask {
		if h.slots[i] == nil {
			return nil
		}
		if key == h.keyOf(h.slots[i]) {
			return h.slots[i]
		}
	}
}

func (h *InfoHtbl) hashToIndex(hash uint32) int {
	const phi32 = 2654435769
	x := (hash * phi32)
	return int(x >> h.shift)
}

func (h *InfoHtbl) grow() {
	old := *h
	h.cap *= 2
	h.shift--
	h.mask = h.mask<<1 + 1
	h.nitems = 0
	h.slots = make([]*Info, 2*len(old.slots))
	for _, slot := range old.slots {
		if slot != nil {
			h.Put(slot)
		}
	}
	if h.nitems != old.nitems {
		panic("flathash grow failed")
	}
}

func (h *InfoHtbl) Dup() *InfoHtbl {
	h2 := *h
	h2.slots = append([]*Info(nil), h.slots...)
	return &h2
}

// List returns a list of the keys in the table
func (h *InfoHtbl) List() []string {
	keys := make([]string, 0, h.nitems)
	for _, slot := range h.slots {
		if slot != nil {
			keys = append(keys, h.keyOf(slot))
		}
	}
	if len(keys) != h.nitems {
		panic("flathash List failed")
	}
	return keys
}

func (h *InfoHtbl) Iter() func() *Info {
	i := -1
	return func() *Info {
		for i++; i < len(h.slots); i++ {
			if h.slots[i] != nil {
				return h.slots[i]
			}
		}
		return nil // end
	}
}

const blockSizeInfo = 2000
const perFingerInfo = 16

func (h *InfoHtbl) Write(st *stor.Stor) uint64 {
	w := st.Writer(blockSizeInfo)
	w.Put2(h.nitems)
	if h.nitems == 0 {
		return w.Close()
	}
	keys := h.List()
	sort.Strings(keys)
	nfingers := 1 + h.nitems/perFingerInfo
	w2 := *w
	for i := 0; i < nfingers; i++ {
		w.Put3(0) // leave room
	}
	fingers := make([]int, 0, nfingers)
	for i, k := range keys {
		if i%16 == 0 {
			fingers = append(fingers, w.Pos())
		}
		h.Get(k).Write(w)
	}
	verify.That(len(fingers) == nfingers)
	for _, f := range fingers {
		w2.Put3(f) // update with actual values
	}
	return w.Close()
}

func ReadInfoHtbl(st *stor.Stor, off uint64) *InfoHtbl {
	r := st.Reader(off)
	nitems := r.Get2()
	t := NewInfoHtbl(nitems)
	if nitems == 0 {
		return t
	}
	nfingers := 1 + nitems/perFingerInfo
	for i := 0; i < nfingers; i++ {
		r.Get3() // skip the fingers
	}
	for i := 0; i < nitems; i++ {
		t.Put(ReadInfo(r))
	}
	return t
}

//-------------------------------------------------------------------

type InfoPacked struct {
	off     uint64
	r       *stor.Reader
	fingers []InfoFinger
}

type InfoFinger struct {
	table string
	pos   int
}

func NewInfoPacked(st *stor.Stor, off uint64) *InfoPacked {
	r := st.Reader(off)
	nitems := r.Get2()
	nfingers := 1 + nitems/perFingerInfo
	fingers := make([]InfoFinger, nfingers)
	for i := 0; i < nfingers; i++ {
		fingers[i].pos = r.Get3()
	}
	for i := 0; i < nfingers; i++ {
		fingers[i].table = r.Pos(fingers[i].pos).GetStr()
	}
	return &InfoPacked{off: off, r: r, fingers: fingers}
}

func (p InfoPacked) Get(table string) *Info {
	p.r.Pos(p.binarySearch(table))
	count := 0
	for {
		ti := ReadInfo(p.r)
		if ti.Table == table {
			return ti
		}
		count++
		if count > 20 {
			panic("linear search too long")
		}
	}
}

func (p InfoPacked) binarySearch(table string) int {
	i, j := 0, len(p.fingers)
	count := 0
	for i < j {
		h := int(uint(i+j) >> 1) // i ≤ h < j
		if table >= p.fingers[h].table {
			i = h + 1
		} else {
			j = h
		}
		count++
		if count > 20 {
			panic("binary search too long")
		}
	}
	// i is first one greater, so we want i-1
	return int(p.fingers[i-1].pos)
}

func (p InfoPacked) Offset() uint64 {
	return p.off
}
