// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright Suneido Software Corp. All rights reserved.
// Governed by the MIT license found in the LICENSE file.

package meta

import (
	"math/bits"
	"sort"

	"github.com/apmckinlay/gsuneido/database/db19/stor"
	"github.com/apmckinlay/gsuneido/util/hash"
	"github.com/apmckinlay/gsuneido/util/verify"
)

type SchemaHtbl struct {
	slots []*Schema
	// nitems is the current number of key/values in the map
	nitems int
	// cap is the limit for nitems before resizing
	cap int
	// shift is used by hashToIndex
	shift int
	// mask is used to wrap around
	mask int
}

// NewSchemaHtbl creates a new SchemaHtbl with roughly the specified capacity
func NewSchemaHtbl(cap int) *SchemaHtbl {
	nextPow2 := func(n int) (int, int) {
		bl := bits.Len(uint(n))
		return 1 << bl, 32 - bl
	}
	const loadPercent = 70
	if cap < 9 {
		cap = 9
	}
	size, shift := nextPow2(cap * 100 / loadPercent)
	return &SchemaHtbl{slots: make([]*Schema, size),
		shift: shift, mask: size - 1, cap: size * loadPercent / 100}
}

func (h *SchemaHtbl) Put(item *Schema) {
	if h.nitems >= h.cap {
		h.grow()
	}
	key := item.Table
	for i := h.hashToIndex(hash.HashString(key)); ; i = (i + 1) & h.mask {
		if h.slots[i] == nil {
			h.nitems++
		} else if h.slots[i].Table != key {
			continue
		}
		h.slots[i] = item
		return
	}
}

func (h *SchemaHtbl) Get(key string) *Schema {
	if h == nil {
		return nil
	}
	for i := h.hashToIndex(hash.HashString(key)); ; i = (i + 1) & h.mask {
		if h.slots[i] == nil {
			return nil
		}
		if key == h.slots[i].Table {
			return h.slots[i]
		}
	}
}

func (h *SchemaHtbl) hashToIndex(hash uint32) int {
	const phi32 = 2654435769
	x := (hash * phi32)
	return int(x >> h.shift)
}

func (h *SchemaHtbl) grow() {
	old := *h
	h.cap *= 2
	h.shift--
	h.mask = h.mask<<1 + 1
	h.nitems = 0
	h.slots = make([]*Schema, 2*len(old.slots))
	for _, slot := range old.slots {
		if slot != nil {
			h.Put(slot)
		}
	}
	if h.nitems != old.nitems {
		panic("metahtbl grow failed")
	}
}

func (h *SchemaHtbl) Dup() *SchemaHtbl {
	h2 := *h
	h2.slots = append([]*Schema(nil), h.slots...)
	return &h2
}

// List returns a list of the keys in the table
func (h *SchemaHtbl) List() []string {
	keys := make([]string, 0, h.nitems)
	for _, slot := range h.slots {
		if slot != nil {
			keys = append(keys, slot.Table)
		}
	}
	if len(keys) != h.nitems {
		panic("metahtbl List failed")
	}
	return keys
}

func (h *SchemaHtbl) Iter() func() *Schema {
	i := -1
	return func() *Schema {
		for i++; i < len(h.slots); i++ {
			if h.slots[i] != nil {
				return h.slots[i]
			}
		}
		return nil // end
	}
}

const blockSizeSchema = 2000
const perFingerSchema = 16

func (h *SchemaHtbl) Write(st *stor.Stor) uint64 {
	if h.nitems == 0 {
		off, buf := st.Alloc(2)
		stor.NewWriter(buf).Put2(0)
		return off
	}
	nfingers := 1 + h.nitems/perFingerSchema
	size := 2 + 3*nfingers
	iter := h.Iter()
	for it := iter(); it != nil; it = iter() {
		size += it.storSize()
	}
	off, buf := st.Alloc(size)
	w := stor.NewWriter(buf)
	w.Put2(h.nitems)

	keys := h.List()
	sort.Strings(keys)
	w2 := *w
	for i := 0; i < nfingers; i++ {
		w.Put3(0) // leave room
	}
	fingers := make([]int, 0, nfingers)
	for i, k := range keys {
		if i%16 == 0 {
			fingers = append(fingers, w.Len())
		}
		h.Get(k).Write(w)
	}
	verify.That(len(fingers) == nfingers)
	for _, f := range fingers {
		w2.Put3(f) // update with actual values
	}
	return off
}

func ReadSchemaHtbl(st *stor.Stor, off uint64) *SchemaHtbl {
	r := st.Reader(off)
	nitems := r.Get2()
	t := NewSchemaHtbl(nitems)
	if nitems == 0 {
		return t
	}
	nfingers := 1 + nitems/perFingerSchema
	for i := 0; i < nfingers; i++ {
		r.Get3() // skip the fingers
	}
	for i := 0; i < nitems; i++ {
		t.Put(ReadSchema(st, r))
	}
	return t
}

//-------------------------------------------------------------------

type SchemaPacked struct {
	stor    *stor.Stor
	off     uint64
	buf     []byte
	fingers []SchemaFinger
}

type SchemaFinger struct {
	table string
	pos   int
}

func NewSchemaPacked(st *stor.Stor, off uint64) *SchemaPacked {
	buf := st.Data(off)
	r := stor.NewReader(buf)
	nitems := r.Get2()
	nfingers := 1 + nitems/perFingerSchema
	fingers := make([]SchemaFinger, nfingers)
	for i := 0; i < nfingers; i++ {
		fingers[i].pos = r.Get3()
	}
	for i := 0; i < nfingers; i++ {
		fingers[i].table = stor.NewReader(buf[fingers[i].pos:]).GetStr()
	}
	return &SchemaPacked{stor: st, off: off, buf: buf, fingers: fingers}
}

func (p SchemaPacked) Get(key string) *Schema {
	pos := p.binarySearch(key)
	r := stor.NewReader(p.buf[pos:])
	count := 0
	for {
		item := ReadSchema(p.stor, r)
		if item.Table == key {
			return item
		}
		count++
		if count > 20 {
			panic("linear search too long")
		}
	}
}

// binarySearch does a binary search of the fingers
func (p SchemaPacked) binarySearch(table string) int {
	i, j := 0, len(p.fingers)
	count := 0
	for i < j {
		h := int(uint(i+j) >> 1) // i ≤ h < j
		if table >= p.fingers[h].table {
			i = h + 1
		} else {
			j = h
		}
		count++
		if count > 20 {
			panic("binary search too long")
		}
	}
	// i is first one greater, so we want i-1
	return int(p.fingers[i-1].pos)
}

func (p SchemaPacked) Offset() uint64 {
	return p.off
}
